/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// DiskScheduleSpecApplyConfiguration represents a declarative configuration of the DiskScheduleSpec type for use
// with apply.
//
// DiskScheduleSpec defines the desired state of the Longhorn disk schedule
type DiskScheduleSpecApplyConfiguration struct {
	// Disk name from node CR
	Name *string `json:"name,omitempty"`
	// Node ID that the disk locates
	NodeID *string `json:"nodeID,omitempty"`
	// Scheduling requests for volume replicas
	Replicas map[string]int64 `json:"replicas,omitempty"`
	// Scheduling requests for backing images
	BackingImages map[string]int64 `json:"backingImages,omitempty"`
}

// DiskScheduleSpecApplyConfiguration constructs a declarative configuration of the DiskScheduleSpec type for use with
// apply.
func DiskScheduleSpec() *DiskScheduleSpecApplyConfiguration {
	return &DiskScheduleSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DiskScheduleSpecApplyConfiguration) WithName(value string) *DiskScheduleSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithNodeID sets the NodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeID field is set to the value of the last call.
func (b *DiskScheduleSpecApplyConfiguration) WithNodeID(value string) *DiskScheduleSpecApplyConfiguration {
	b.NodeID = &value
	return b
}

// WithReplicas puts the entries into the Replicas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Replicas field,
// overwriting an existing map entries in Replicas field with the same key.
func (b *DiskScheduleSpecApplyConfiguration) WithReplicas(entries map[string]int64) *DiskScheduleSpecApplyConfiguration {
	if b.Replicas == nil && len(entries) > 0 {
		b.Replicas = make(map[string]int64, len(entries))
	}
	for k, v := range entries {
		b.Replicas[k] = v
	}
	return b
}

// WithBackingImages puts the entries into the BackingImages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the BackingImages field,
// overwriting an existing map entries in BackingImages field with the same key.
func (b *DiskScheduleSpecApplyConfiguration) WithBackingImages(entries map[string]int64) *DiskScheduleSpecApplyConfiguration {
	if b.BackingImages == nil && len(entries) > 0 {
		b.BackingImages = make(map[string]int64, len(entries))
	}
	for k, v := range entries {
		b.BackingImages[k] = v
	}
	return b
}
