/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// DiskScheduledResourcesStatusApplyConfiguration represents a declarative configuration of the DiskScheduledResourcesStatus type for use
// with apply.
type DiskScheduledResourcesStatusApplyConfiguration struct {
	Result        *longhornv1beta2.DiskScheduleResult `json:"result,omitempty"`
	RequiredSize  *int64                              `json:"requiredSize,omitempty"`
	ScheduledSize *int64                              `json:"scheduledSize,omitempty"`
}

// DiskScheduledResourcesStatusApplyConfiguration constructs a declarative configuration of the DiskScheduledResourcesStatus type for use with
// apply.
func DiskScheduledResourcesStatus() *DiskScheduledResourcesStatusApplyConfiguration {
	return &DiskScheduledResourcesStatusApplyConfiguration{}
}

// WithResult sets the Result field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Result field is set to the value of the last call.
func (b *DiskScheduledResourcesStatusApplyConfiguration) WithResult(value longhornv1beta2.DiskScheduleResult) *DiskScheduledResourcesStatusApplyConfiguration {
	b.Result = &value
	return b
}

// WithRequiredSize sets the RequiredSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredSize field is set to the value of the last call.
func (b *DiskScheduledResourcesStatusApplyConfiguration) WithRequiredSize(value int64) *DiskScheduledResourcesStatusApplyConfiguration {
	b.RequiredSize = &value
	return b
}

// WithScheduledSize sets the ScheduledSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScheduledSize field is set to the value of the last call.
func (b *DiskScheduledResourcesStatusApplyConfiguration) WithScheduledSize(value int64) *DiskScheduledResourcesStatusApplyConfiguration {
	b.ScheduledSize = &value
	return b
}
