/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// DiskScheduleStatusApplyConfiguration represents a declarative configuration of the DiskScheduleStatus type for use
// with apply.
type DiskScheduleStatusApplyConfiguration struct {
	ScheduledReplicaStatus      map[string]*longhornv1beta2.DiskScheduledResourcesStatus `json:"scheduledReplicaStatus,omitempty"`
	ScheduledBackingImageStatus map[string]*longhornv1beta2.DiskScheduledResourcesStatus `json:"scheduledBackingImageStatus,omitempty"`
	StorageScheduled            *int64                                                   `json:"storageScheduled,omitempty"`
	Conditions                  []ConditionApplyConfiguration                            `json:"conditions,omitempty"`
}

// DiskScheduleStatusApplyConfiguration constructs a declarative configuration of the DiskScheduleStatus type for use with
// apply.
func DiskScheduleStatus() *DiskScheduleStatusApplyConfiguration {
	return &DiskScheduleStatusApplyConfiguration{}
}

// WithScheduledReplicaStatus puts the entries into the ScheduledReplicaStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ScheduledReplicaStatus field,
// overwriting an existing map entries in ScheduledReplicaStatus field with the same key.
func (b *DiskScheduleStatusApplyConfiguration) WithScheduledReplicaStatus(entries map[string]*longhornv1beta2.DiskScheduledResourcesStatus) *DiskScheduleStatusApplyConfiguration {
	if b.ScheduledReplicaStatus == nil && len(entries) > 0 {
		b.ScheduledReplicaStatus = make(map[string]*longhornv1beta2.DiskScheduledResourcesStatus, len(entries))
	}
	for k, v := range entries {
		b.ScheduledReplicaStatus[k] = v
	}
	return b
}

// WithScheduledBackingImageStatus puts the entries into the ScheduledBackingImageStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ScheduledBackingImageStatus field,
// overwriting an existing map entries in ScheduledBackingImageStatus field with the same key.
func (b *DiskScheduleStatusApplyConfiguration) WithScheduledBackingImageStatus(entries map[string]*longhornv1beta2.DiskScheduledResourcesStatus) *DiskScheduleStatusApplyConfiguration {
	if b.ScheduledBackingImageStatus == nil && len(entries) > 0 {
		b.ScheduledBackingImageStatus = make(map[string]*longhornv1beta2.DiskScheduledResourcesStatus, len(entries))
	}
	for k, v := range entries {
		b.ScheduledBackingImageStatus[k] = v
	}
	return b
}

// WithStorageScheduled sets the StorageScheduled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageScheduled field is set to the value of the last call.
func (b *DiskScheduleStatusApplyConfiguration) WithStorageScheduled(value int64) *DiskScheduleStatusApplyConfiguration {
	b.StorageScheduled = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DiskScheduleStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *DiskScheduleStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
