/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// EngineRelocationApplyConfiguration represents a declarative configuration of the EngineRelocation type for use
// with apply.
//
// EngineRelocation records the relocation metadata of an engine during an
// instance manager upgrade.
type EngineRelocationApplyConfiguration struct {
	// OriginalNodeID is the node where the engine was originally running.
	OriginalNodeID *string `json:"originalNodeID,omitempty"`
	// TemporaryNodeID is the node the engine is temporarily relocated to
	// while the source instance manager is being upgraded.
	TemporaryNodeID *string `json:"temporaryNodeID,omitempty"`
	// SnapshotName is the name of the pre-upgrade snapshot created for this
	// volume before relocation, used to support fast replica rebuild. It is
	// only set when the TakeSnapshotBeforeV2DataEngineUpgrade setting is
	// enabled and snapshot data integrity checking is enabled for the volume.
	SnapshotName *string `json:"snapshotName,omitempty"`
}

// EngineRelocationApplyConfiguration constructs a declarative configuration of the EngineRelocation type for use with
// apply.
func EngineRelocation() *EngineRelocationApplyConfiguration {
	return &EngineRelocationApplyConfiguration{}
}

// WithOriginalNodeID sets the OriginalNodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OriginalNodeID field is set to the value of the last call.
func (b *EngineRelocationApplyConfiguration) WithOriginalNodeID(value string) *EngineRelocationApplyConfiguration {
	b.OriginalNodeID = &value
	return b
}

// WithTemporaryNodeID sets the TemporaryNodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemporaryNodeID field is set to the value of the last call.
func (b *EngineRelocationApplyConfiguration) WithTemporaryNodeID(value string) *EngineRelocationApplyConfiguration {
	b.TemporaryNodeID = &value
	return b
}

// WithSnapshotName sets the SnapshotName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotName field is set to the value of the last call.
func (b *EngineRelocationApplyConfiguration) WithSnapshotName(value string) *EngineRelocationApplyConfiguration {
	b.SnapshotName = &value
	return b
}
