/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// EngineFrontendSpecApplyConfiguration represents a declarative configuration of the EngineFrontendSpec type for use
// with apply.
//
// EngineFrontendSpec defines the desired state of the Longhorn engine frontend (v2 initiator)
type EngineFrontendSpecApplyConfiguration struct {
	// Size is the desired size of the frontend device in bytes, as requested
	// by the volume owner. The EngineFrontend controller drives the frontend
	// device toward this size independently of the engine's target size.
	Size     *int64                          `json:"size,omitempty"`
	Frontend *longhornv1beta2.VolumeFrontend `json:"frontend,omitempty"`
	// ublkQueueDepth controls the depth of each queue for ublk frontend.
	UblkQueueDepth *int `json:"ublkQueueDepth,omitempty"`
	// ublkNumberOfQueue controls the number of queues for ublk frontend.
	UblkNumberOfQueue *int `json:"ublkNumberOfQueue,omitempty"`
	// TargetIP is the IP address of the v2 engine target
	TargetIP *string `json:"targetIP,omitempty"`
	// TargetPort is the port of the v2 engine target
	TargetPort *int `json:"targetPort,omitempty"`
	// EngineName is the name of the v2 engine target (required for EngineFrontend instance creation)
	EngineName      *string `json:"engineName,omitempty"`
	DisableFrontend *bool   `json:"disableFrontend,omitempty"`
	Active          *bool   `json:"active,omitempty"`
}

// EngineFrontendSpecApplyConfiguration constructs a declarative configuration of the EngineFrontendSpec type for use with
// apply.
func EngineFrontendSpec() *EngineFrontendSpecApplyConfiguration {
	return &EngineFrontendSpecApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *EngineFrontendSpecApplyConfiguration) WithSize(value int64) *EngineFrontendSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithFrontend sets the Frontend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Frontend field is set to the value of the last call.
func (b *EngineFrontendSpecApplyConfiguration) WithFrontend(value longhornv1beta2.VolumeFrontend) *EngineFrontendSpecApplyConfiguration {
	b.Frontend = &value
	return b
}

// WithUblkQueueDepth sets the UblkQueueDepth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UblkQueueDepth field is set to the value of the last call.
func (b *EngineFrontendSpecApplyConfiguration) WithUblkQueueDepth(value int) *EngineFrontendSpecApplyConfiguration {
	b.UblkQueueDepth = &value
	return b
}

// WithUblkNumberOfQueue sets the UblkNumberOfQueue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UblkNumberOfQueue field is set to the value of the last call.
func (b *EngineFrontendSpecApplyConfiguration) WithUblkNumberOfQueue(value int) *EngineFrontendSpecApplyConfiguration {
	b.UblkNumberOfQueue = &value
	return b
}

// WithTargetIP sets the TargetIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetIP field is set to the value of the last call.
func (b *EngineFrontendSpecApplyConfiguration) WithTargetIP(value string) *EngineFrontendSpecApplyConfiguration {
	b.TargetIP = &value
	return b
}

// WithTargetPort sets the TargetPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPort field is set to the value of the last call.
func (b *EngineFrontendSpecApplyConfiguration) WithTargetPort(value int) *EngineFrontendSpecApplyConfiguration {
	b.TargetPort = &value
	return b
}

// WithEngineName sets the EngineName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EngineName field is set to the value of the last call.
func (b *EngineFrontendSpecApplyConfiguration) WithEngineName(value string) *EngineFrontendSpecApplyConfiguration {
	b.EngineName = &value
	return b
}

// WithDisableFrontend sets the DisableFrontend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisableFrontend field is set to the value of the last call.
func (b *EngineFrontendSpecApplyConfiguration) WithDisableFrontend(value bool) *EngineFrontendSpecApplyConfiguration {
	b.DisableFrontend = &value
	return b
}

// WithActive sets the Active field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Active field is set to the value of the last call.
func (b *EngineFrontendSpecApplyConfiguration) WithActive(value bool) *EngineFrontendSpecApplyConfiguration {
	b.Active = &value
	return b
}
