/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// EngineFrontendStatusApplyConfiguration represents a declarative configuration of the EngineFrontendStatus type for use
// with apply.
//
// EngineFrontendStatus defines the observed state of the Longhorn engine frontend
type EngineFrontendStatusApplyConfiguration struct {
	// CurrentSize is the current size of the frontend device in bytes, as
	// observed from the data plane. It is 0 while the engine frontend is not
	// running.
	CurrentSize *int64 `json:"currentSize,omitempty"`
	// Endpoint is the initiator endpoint (e.g., /dev/longhorn/vol-name)
	Endpoint *string `json:"endpoint,omitempty"`
	// TargetIP is the currently connected IP address of the v2 engine target
	TargetIP *string `json:"targetIP,omitempty"`
	// TargetPort is the currently connected port of the v2 engine target
	TargetPort *int `json:"targetPort,omitempty"`
	// ActivePath is the currently active frontend path address.
	ActivePath *string `json:"activePath,omitempty"`
	// PreferredPath is the preferred frontend path address.
	PreferredPath *string `json:"preferredPath,omitempty"`
	// Paths describes the currently known frontend multipath state.
	Paths []EngineFrontendNvmeTCPPathApplyConfiguration `json:"paths,omitempty"`
	// SwitchoverPhase is the last completed switchover phase reported by the data plane.
	SwitchoverPhase *longhornv1beta2.EngineFrontendSwitchoverPhase `json:"switchoverPhase,omitempty"`
}

// EngineFrontendStatusApplyConfiguration constructs a declarative configuration of the EngineFrontendStatus type for use with
// apply.
func EngineFrontendStatus() *EngineFrontendStatusApplyConfiguration {
	return &EngineFrontendStatusApplyConfiguration{}
}

// WithCurrentSize sets the CurrentSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentSize field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithCurrentSize(value int64) *EngineFrontendStatusApplyConfiguration {
	b.CurrentSize = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithEndpoint(value string) *EngineFrontendStatusApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithTargetIP sets the TargetIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetIP field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithTargetIP(value string) *EngineFrontendStatusApplyConfiguration {
	b.TargetIP = &value
	return b
}

// WithTargetPort sets the TargetPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPort field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithTargetPort(value int) *EngineFrontendStatusApplyConfiguration {
	b.TargetPort = &value
	return b
}

// WithActivePath sets the ActivePath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActivePath field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithActivePath(value string) *EngineFrontendStatusApplyConfiguration {
	b.ActivePath = &value
	return b
}

// WithPreferredPath sets the PreferredPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreferredPath field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithPreferredPath(value string) *EngineFrontendStatusApplyConfiguration {
	b.PreferredPath = &value
	return b
}

// WithPaths adds the given value to the Paths field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Paths field.
func (b *EngineFrontendStatusApplyConfiguration) WithPaths(values ...*EngineFrontendNvmeTCPPathApplyConfiguration) *EngineFrontendStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPaths")
		}
		b.Paths = append(b.Paths, *values[i])
	}
	return b
}

// WithSwitchoverPhase sets the SwitchoverPhase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchoverPhase field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithSwitchoverPhase(value longhornv1beta2.EngineFrontendSwitchoverPhase) *EngineFrontendStatusApplyConfiguration {
	b.SwitchoverPhase = &value
	return b
}
