/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// EngineFrontendStatusApplyConfiguration represents a declarative configuration of the EngineFrontendStatus type for use
// with apply.
//
// EngineFrontendStatus defines the observed state of the Longhorn engine frontend
type EngineFrontendStatusApplyConfiguration struct {
	// Endpoint is the initiator endpoint (e.g., /dev/longhorn/vol-name)
	Endpoint *string `json:"endpoint,omitempty"`
	// TargetIP is the currently connected IP address of the v2 engine target
	TargetIP *string `json:"targetIP,omitempty"`
	// TargetPort is the currently connected port of the v2 engine target
	TargetPort *int `json:"targetPort,omitempty"`
}

// EngineFrontendStatusApplyConfiguration constructs a declarative configuration of the EngineFrontendStatus type for use with
// apply.
func EngineFrontendStatus() *EngineFrontendStatusApplyConfiguration {
	return &EngineFrontendStatusApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithEndpoint(value string) *EngineFrontendStatusApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithTargetIP sets the TargetIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetIP field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithTargetIP(value string) *EngineFrontendStatusApplyConfiguration {
	b.TargetIP = &value
	return b
}

// WithTargetPort sets the TargetPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPort field is set to the value of the last call.
func (b *EngineFrontendStatusApplyConfiguration) WithTargetPort(value int) *EngineFrontendStatusApplyConfiguration {
	b.TargetPort = &value
	return b
}
