/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// EngineFrontendNvmeTCPPathApplyConfiguration represents a declarative configuration of the EngineFrontendNvmeTCPPath type for use
// with apply.
type EngineFrontendNvmeTCPPathApplyConfiguration struct {
	TargetIP   *string `json:"targetIP,omitempty"`
	TargetPort *int    `json:"targetPort,omitempty"`
	EngineName *string `json:"engineName,omitempty"`
	NQN        *string `json:"nqn,omitempty"`
	NGUID      *string `json:"nguid,omitempty"`
	ANAState   *string `json:"anaState,omitempty"`
}

// EngineFrontendNvmeTCPPathApplyConfiguration constructs a declarative configuration of the EngineFrontendNvmeTCPPath type for use with
// apply.
func EngineFrontendNvmeTCPPath() *EngineFrontendNvmeTCPPathApplyConfiguration {
	return &EngineFrontendNvmeTCPPathApplyConfiguration{}
}

// WithTargetIP sets the TargetIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetIP field is set to the value of the last call.
func (b *EngineFrontendNvmeTCPPathApplyConfiguration) WithTargetIP(value string) *EngineFrontendNvmeTCPPathApplyConfiguration {
	b.TargetIP = &value
	return b
}

// WithTargetPort sets the TargetPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPort field is set to the value of the last call.
func (b *EngineFrontendNvmeTCPPathApplyConfiguration) WithTargetPort(value int) *EngineFrontendNvmeTCPPathApplyConfiguration {
	b.TargetPort = &value
	return b
}

// WithEngineName sets the EngineName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EngineName field is set to the value of the last call.
func (b *EngineFrontendNvmeTCPPathApplyConfiguration) WithEngineName(value string) *EngineFrontendNvmeTCPPathApplyConfiguration {
	b.EngineName = &value
	return b
}

// WithNQN sets the NQN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NQN field is set to the value of the last call.
func (b *EngineFrontendNvmeTCPPathApplyConfiguration) WithNQN(value string) *EngineFrontendNvmeTCPPathApplyConfiguration {
	b.NQN = &value
	return b
}

// WithNGUID sets the NGUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NGUID field is set to the value of the last call.
func (b *EngineFrontendNvmeTCPPathApplyConfiguration) WithNGUID(value string) *EngineFrontendNvmeTCPPathApplyConfiguration {
	b.NGUID = &value
	return b
}

// WithANAState sets the ANAState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ANAState field is set to the value of the last call.
func (b *EngineFrontendNvmeTCPPathApplyConfiguration) WithANAState(value string) *EngineFrontendNvmeTCPPathApplyConfiguration {
	b.ANAState = &value
	return b
}
