/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// HealthAttributeApplyConfiguration represents a declarative configuration of the HealthAttribute type for use
// with apply.
type HealthAttributeApplyConfiguration struct {
	ID         *uint16 `json:"id,omitempty"`
	Name       *string `json:"name,omitempty"`
	Value      *uint16 `json:"value,omitempty"`
	Worst      *uint16 `json:"worst,omitempty"`
	Threshold  *uint16 `json:"threshold,omitempty"`
	RawValue   *uint64 `json:"rawValue,omitempty"`
	RawString  *string `json:"rawString,omitempty"`
	WhenFailed *string `json:"whenFailed,omitempty"`
}

// HealthAttributeApplyConfiguration constructs a declarative configuration of the HealthAttribute type for use with
// apply.
func HealthAttribute() *HealthAttributeApplyConfiguration {
	return &HealthAttributeApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *HealthAttributeApplyConfiguration) WithID(value uint16) *HealthAttributeApplyConfiguration {
	b.ID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HealthAttributeApplyConfiguration) WithName(value string) *HealthAttributeApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *HealthAttributeApplyConfiguration) WithValue(value uint16) *HealthAttributeApplyConfiguration {
	b.Value = &value
	return b
}

// WithWorst sets the Worst field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Worst field is set to the value of the last call.
func (b *HealthAttributeApplyConfiguration) WithWorst(value uint16) *HealthAttributeApplyConfiguration {
	b.Worst = &value
	return b
}

// WithThreshold sets the Threshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Threshold field is set to the value of the last call.
func (b *HealthAttributeApplyConfiguration) WithThreshold(value uint16) *HealthAttributeApplyConfiguration {
	b.Threshold = &value
	return b
}

// WithRawValue sets the RawValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RawValue field is set to the value of the last call.
func (b *HealthAttributeApplyConfiguration) WithRawValue(value uint64) *HealthAttributeApplyConfiguration {
	b.RawValue = &value
	return b
}

// WithRawString sets the RawString field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RawString field is set to the value of the last call.
func (b *HealthAttributeApplyConfiguration) WithRawString(value string) *HealthAttributeApplyConfiguration {
	b.RawString = &value
	return b
}

// WithWhenFailed sets the WhenFailed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WhenFailed field is set to the value of the last call.
func (b *HealthAttributeApplyConfiguration) WithWhenFailed(value string) *HealthAttributeApplyConfiguration {
	b.WhenFailed = &value
	return b
}
