/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// HealthDataApplyConfiguration represents a declarative configuration of the HealthData type for use
// with apply.
type HealthDataApplyConfiguration struct {
	Source          *longhornv1beta2.HealthDataSource       `json:"source,omitempty"`
	ModelName       *string                                 `json:"modelName,omitempty"`
	SerialNumber    *string                                 `json:"serialNumber,omitempty"`
	FirmwareVersion *string                                 `json:"firmwareVersion,omitempty"`
	Capacity        *uint64                                 `json:"capacity,omitempty"`
	HealthStatus    *longhornv1beta2.HealthDataHealthStatus `json:"healthStatus,omitempty"`
	DiskName        *string                                 `json:"diskName,omitempty"`
	DiskType        *string                                 `json:"diskType,omitempty"`
	Temperature     *byte                                   `json:"temperature,omitempty"`
	Attributes      []*longhornv1beta2.HealthAttribute      `json:"attributes,omitempty"`
}

// HealthDataApplyConfiguration constructs a declarative configuration of the HealthData type for use with
// apply.
func HealthData() *HealthDataApplyConfiguration {
	return &HealthDataApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *HealthDataApplyConfiguration) WithSource(value longhornv1beta2.HealthDataSource) *HealthDataApplyConfiguration {
	b.Source = &value
	return b
}

// WithModelName sets the ModelName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelName field is set to the value of the last call.
func (b *HealthDataApplyConfiguration) WithModelName(value string) *HealthDataApplyConfiguration {
	b.ModelName = &value
	return b
}

// WithSerialNumber sets the SerialNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SerialNumber field is set to the value of the last call.
func (b *HealthDataApplyConfiguration) WithSerialNumber(value string) *HealthDataApplyConfiguration {
	b.SerialNumber = &value
	return b
}

// WithFirmwareVersion sets the FirmwareVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirmwareVersion field is set to the value of the last call.
func (b *HealthDataApplyConfiguration) WithFirmwareVersion(value string) *HealthDataApplyConfiguration {
	b.FirmwareVersion = &value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *HealthDataApplyConfiguration) WithCapacity(value uint64) *HealthDataApplyConfiguration {
	b.Capacity = &value
	return b
}

// WithHealthStatus sets the HealthStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthStatus field is set to the value of the last call.
func (b *HealthDataApplyConfiguration) WithHealthStatus(value longhornv1beta2.HealthDataHealthStatus) *HealthDataApplyConfiguration {
	b.HealthStatus = &value
	return b
}

// WithDiskName sets the DiskName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskName field is set to the value of the last call.
func (b *HealthDataApplyConfiguration) WithDiskName(value string) *HealthDataApplyConfiguration {
	b.DiskName = &value
	return b
}

// WithDiskType sets the DiskType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskType field is set to the value of the last call.
func (b *HealthDataApplyConfiguration) WithDiskType(value string) *HealthDataApplyConfiguration {
	b.DiskType = &value
	return b
}

// WithTemperature sets the Temperature field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Temperature field is set to the value of the last call.
func (b *HealthDataApplyConfiguration) WithTemperature(value byte) *HealthDataApplyConfiguration {
	b.Temperature = &value
	return b
}

// WithAttributes adds the given value to the Attributes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Attributes field.
func (b *HealthDataApplyConfiguration) WithAttributes(values ...**longhornv1beta2.HealthAttribute) *HealthDataApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAttributes")
		}
		b.Attributes = append(b.Attributes, *values[i])
	}
	return b
}
