/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// InstanceManagerUpgradeControlStatusApplyConfiguration represents a declarative configuration of the InstanceManagerUpgradeControlStatus type for use
// with apply.
//
// InstanceManagerUpgradeControlStatus defines the observed state of the
// InstanceManagerUpgradeControl.
type InstanceManagerUpgradeControlStatusApplyConfiguration struct {
	// OwnerID is the ID of the Longhorn manager pod that currently owns this CR.
	OwnerID *string `json:"ownerID,omitempty"`
	// CurrentNode is the name of the node that is actively being upgraded.
	// Empty when no upgrade is in progress.
	CurrentNode *string `json:"currentNode,omitempty"`
	// Nodes holds the upgrade status for every node in the cluster.
	// The map is pre-populated with all nodes when a new cycle starts.
	Nodes map[string]NodeUpgradeInfoApplyConfiguration `json:"nodes,omitempty"`
}

// InstanceManagerUpgradeControlStatusApplyConfiguration constructs a declarative configuration of the InstanceManagerUpgradeControlStatus type for use with
// apply.
func InstanceManagerUpgradeControlStatus() *InstanceManagerUpgradeControlStatusApplyConfiguration {
	return &InstanceManagerUpgradeControlStatusApplyConfiguration{}
}

// WithOwnerID sets the OwnerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerID field is set to the value of the last call.
func (b *InstanceManagerUpgradeControlStatusApplyConfiguration) WithOwnerID(value string) *InstanceManagerUpgradeControlStatusApplyConfiguration {
	b.OwnerID = &value
	return b
}

// WithCurrentNode sets the CurrentNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentNode field is set to the value of the last call.
func (b *InstanceManagerUpgradeControlStatusApplyConfiguration) WithCurrentNode(value string) *InstanceManagerUpgradeControlStatusApplyConfiguration {
	b.CurrentNode = &value
	return b
}

// WithNodes puts the entries into the Nodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Nodes field,
// overwriting an existing map entries in Nodes field with the same key.
func (b *InstanceManagerUpgradeControlStatusApplyConfiguration) WithNodes(entries map[string]NodeUpgradeInfoApplyConfiguration) *InstanceManagerUpgradeControlStatusApplyConfiguration {
	if b.Nodes == nil && len(entries) > 0 {
		b.Nodes = make(map[string]NodeUpgradeInfoApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Nodes[k] = v
	}
	return b
}
