/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// InstanceManagerUpgradeStatusApplyConfiguration represents a declarative configuration of the InstanceManagerUpgradeStatus type for use
// with apply.
//
// InstanceManagerUpgradeStatus defines the observed state of the InstanceManagerUpgrade.
type InstanceManagerUpgradeStatusApplyConfiguration struct {
	// OwnerID is the owner node ID of this InstanceManagerUpgrade.
	OwnerID *string `json:"ownerID,omitempty"`
	// State indicates the overall progress of the instance manager upgrade.
	State *longhornv1beta2.InstanceManagerUpgradeState `json:"state,omitempty"`
	// Engines records the relocation plan for each engine managed by the source
	// instance manager. The map key is the volume name.
	Engines map[string]EngineRelocationApplyConfiguration `json:"engines,omitempty"`
	// StartedAt records when the upgrade transitioned out of Pending and began
	// active work. It is used to enforce the upgrade timeout. This timestamp is
	// set once and never reset, providing a single global timeline for the entire upgrade.
	StartedAt *string `json:"startedAt,omitempty"`
	// AbortRequested is set by the controller when an abort condition is detected
	// (e.g., timeout, target image change). This is controller-owned state.
	AbortRequested *bool `json:"abortRequested,omitempty"`
	// AbortReason explains why AbortRequested was set (e.g., "timeout", "target-image-changed").
	// This provides observability and helps the upgrade-control controller distinguish
	// between different abort scenarios.
	AbortReason *string `json:"abortReason,omitempty"`
	// ErrorMsg records the terminal error encountered during the upgrade, if any.
	ErrorMsg *string `json:"errorMsg,omitempty"`
	// Conditions records the current conditions of the upgrade.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// InstanceManagerUpgradeStatusApplyConfiguration constructs a declarative configuration of the InstanceManagerUpgradeStatus type for use with
// apply.
func InstanceManagerUpgradeStatus() *InstanceManagerUpgradeStatusApplyConfiguration {
	return &InstanceManagerUpgradeStatusApplyConfiguration{}
}

// WithOwnerID sets the OwnerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerID field is set to the value of the last call.
func (b *InstanceManagerUpgradeStatusApplyConfiguration) WithOwnerID(value string) *InstanceManagerUpgradeStatusApplyConfiguration {
	b.OwnerID = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *InstanceManagerUpgradeStatusApplyConfiguration) WithState(value longhornv1beta2.InstanceManagerUpgradeState) *InstanceManagerUpgradeStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithEngines puts the entries into the Engines field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Engines field,
// overwriting an existing map entries in Engines field with the same key.
func (b *InstanceManagerUpgradeStatusApplyConfiguration) WithEngines(entries map[string]EngineRelocationApplyConfiguration) *InstanceManagerUpgradeStatusApplyConfiguration {
	if b.Engines == nil && len(entries) > 0 {
		b.Engines = make(map[string]EngineRelocationApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Engines[k] = v
	}
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *InstanceManagerUpgradeStatusApplyConfiguration) WithStartedAt(value string) *InstanceManagerUpgradeStatusApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithAbortRequested sets the AbortRequested field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AbortRequested field is set to the value of the last call.
func (b *InstanceManagerUpgradeStatusApplyConfiguration) WithAbortRequested(value bool) *InstanceManagerUpgradeStatusApplyConfiguration {
	b.AbortRequested = &value
	return b
}

// WithAbortReason sets the AbortReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AbortReason field is set to the value of the last call.
func (b *InstanceManagerUpgradeStatusApplyConfiguration) WithAbortReason(value string) *InstanceManagerUpgradeStatusApplyConfiguration {
	b.AbortReason = &value
	return b
}

// WithErrorMsg sets the ErrorMsg field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ErrorMsg field is set to the value of the last call.
func (b *InstanceManagerUpgradeStatusApplyConfiguration) WithErrorMsg(value string) *InstanceManagerUpgradeStatusApplyConfiguration {
	b.ErrorMsg = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *InstanceManagerUpgradeStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *InstanceManagerUpgradeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
