/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// InstanceManagerUpgradeSpecApplyConfiguration represents a declarative configuration of the InstanceManagerUpgradeSpec type for use
// with apply.
//
// InstanceManagerUpgradeSpec defines the desired state of the InstanceManagerUpgrade.
type InstanceManagerUpgradeSpecApplyConfiguration struct {
	// NodeID is the node where the source instance manager is running.
	// Engines managed by the source instance manager are temporarily relocated
	// away from this node during the upgrade and restored to it afterward.
	NodeID *string `json:"nodeID,omitempty"`
	// TargetImage is the desired instance manager image after upgrade.
	TargetImage *string `json:"targetImage,omitempty"`
}

// InstanceManagerUpgradeSpecApplyConfiguration constructs a declarative configuration of the InstanceManagerUpgradeSpec type for use with
// apply.
func InstanceManagerUpgradeSpec() *InstanceManagerUpgradeSpecApplyConfiguration {
	return &InstanceManagerUpgradeSpecApplyConfiguration{}
}

// WithNodeID sets the NodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeID field is set to the value of the last call.
func (b *InstanceManagerUpgradeSpecApplyConfiguration) WithNodeID(value string) *InstanceManagerUpgradeSpecApplyConfiguration {
	b.NodeID = &value
	return b
}

// WithTargetImage sets the TargetImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetImage field is set to the value of the last call.
func (b *InstanceManagerUpgradeSpecApplyConfiguration) WithTargetImage(value string) *InstanceManagerUpgradeSpecApplyConfiguration {
	b.TargetImage = &value
	return b
}
