/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/api/core/v1"
)

// NodeInstanceManagerResourcesApplyConfiguration represents a declarative configuration of the NodeInstanceManagerResources type for use
// with apply.
//
// NodeInstanceManagerResources overrides the instance manager pod resource requirements
// on this node. A set engine entry replaces the derived pod resource requirements as a whole.
type NodeInstanceManagerResourcesApplyConfiguration struct {
	V2 *v1.ResourceRequirements `json:"v2,omitempty"`
}

// NodeInstanceManagerResourcesApplyConfiguration constructs a declarative configuration of the NodeInstanceManagerResources type for use with
// apply.
func NodeInstanceManagerResources() *NodeInstanceManagerResourcesApplyConfiguration {
	return &NodeInstanceManagerResourcesApplyConfiguration{}
}

// WithV2 sets the V2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V2 field is set to the value of the last call.
func (b *NodeInstanceManagerResourcesApplyConfiguration) WithV2(value v1.ResourceRequirements) *NodeInstanceManagerResourcesApplyConfiguration {
	b.V2 = &value
	return b
}
