/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// NodeV2DataEngineResourcesApplyConfiguration represents a declarative configuration of the NodeV2DataEngineResources type for use
// with apply.
type NodeV2DataEngineResourcesApplyConfiguration struct {
	// Overrides the data-engine-number-of-cpu-cores setting for this node.
	NumberOfCPUCores *int64 `json:"numberOfCPUCores,omitempty"`
	// Overrides the data-engine-cpu-mask setting for this node (static CPU mask path only).
	CPUMask *string `json:"cpuMask,omitempty"`
	// Overrides the data-engine-memory-size setting for this node.
	MemorySizeMiB *int64 `json:"memorySizeMiB,omitempty"`
	// Overrides the data-engine-hugepage-enabled setting for this node.
	HugepageEnabled *bool `json:"hugepageEnabled,omitempty"`
	// Overrides the data-engine-iobuf-small-pool-size setting for this node.
	IobufSmallPoolSize *int64 `json:"iobufSmallPoolSize,omitempty"`
	// Overrides the data-engine-iobuf-large-pool-size setting for this node.
	IobufLargePoolSize *int64 `json:"iobufLargePoolSize,omitempty"`
}

// NodeV2DataEngineResourcesApplyConfiguration constructs a declarative configuration of the NodeV2DataEngineResources type for use with
// apply.
func NodeV2DataEngineResources() *NodeV2DataEngineResourcesApplyConfiguration {
	return &NodeV2DataEngineResourcesApplyConfiguration{}
}

// WithNumberOfCPUCores sets the NumberOfCPUCores field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NumberOfCPUCores field is set to the value of the last call.
func (b *NodeV2DataEngineResourcesApplyConfiguration) WithNumberOfCPUCores(value int64) *NodeV2DataEngineResourcesApplyConfiguration {
	b.NumberOfCPUCores = &value
	return b
}

// WithCPUMask sets the CPUMask field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPUMask field is set to the value of the last call.
func (b *NodeV2DataEngineResourcesApplyConfiguration) WithCPUMask(value string) *NodeV2DataEngineResourcesApplyConfiguration {
	b.CPUMask = &value
	return b
}

// WithMemorySizeMiB sets the MemorySizeMiB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemorySizeMiB field is set to the value of the last call.
func (b *NodeV2DataEngineResourcesApplyConfiguration) WithMemorySizeMiB(value int64) *NodeV2DataEngineResourcesApplyConfiguration {
	b.MemorySizeMiB = &value
	return b
}

// WithHugepageEnabled sets the HugepageEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HugepageEnabled field is set to the value of the last call.
func (b *NodeV2DataEngineResourcesApplyConfiguration) WithHugepageEnabled(value bool) *NodeV2DataEngineResourcesApplyConfiguration {
	b.HugepageEnabled = &value
	return b
}

// WithIobufSmallPoolSize sets the IobufSmallPoolSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IobufSmallPoolSize field is set to the value of the last call.
func (b *NodeV2DataEngineResourcesApplyConfiguration) WithIobufSmallPoolSize(value int64) *NodeV2DataEngineResourcesApplyConfiguration {
	b.IobufSmallPoolSize = &value
	return b
}

// WithIobufLargePoolSize sets the IobufLargePoolSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IobufLargePoolSize field is set to the value of the last call.
func (b *NodeV2DataEngineResourcesApplyConfiguration) WithIobufLargePoolSize(value int64) *NodeV2DataEngineResourcesApplyConfiguration {
	b.IobufLargePoolSize = &value
	return b
}
