/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// NodeUpgradeInfoApplyConfiguration represents a declarative configuration of the NodeUpgradeInfo type for use
// with apply.
//
// NodeUpgradeInfo records the upgrade status for a single node.
type NodeUpgradeInfoApplyConfiguration struct {
	// State is the current upgrade state for this node.
	State *longhornv1beta2.NodeUpgradeState `json:"state,omitempty"`
	// IMUName is the name of the InstanceManagerUpgrade CR created for this node.
	IMUName *string `json:"imuName,omitempty"`
	// RetryCount tracks how many times the upgrade has been attempted for this node.
	RetryCount *int `json:"retryCount,omitempty"`
	// StartedAt is the RFC3339 timestamp when the upgrade began on this node.
	StartedAt *string `json:"startedAt,omitempty"`
	// CompletedAt is the RFC3339 timestamp when the upgrade finished on this node.
	CompletedAt *string `json:"completedAt,omitempty"`
	// ErrorMsg records the last error encountered while upgrading this node.
	ErrorMsg *string `json:"errorMsg,omitempty"`
}

// NodeUpgradeInfoApplyConfiguration constructs a declarative configuration of the NodeUpgradeInfo type for use with
// apply.
func NodeUpgradeInfo() *NodeUpgradeInfoApplyConfiguration {
	return &NodeUpgradeInfoApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *NodeUpgradeInfoApplyConfiguration) WithState(value longhornv1beta2.NodeUpgradeState) *NodeUpgradeInfoApplyConfiguration {
	b.State = &value
	return b
}

// WithIMUName sets the IMUName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IMUName field is set to the value of the last call.
func (b *NodeUpgradeInfoApplyConfiguration) WithIMUName(value string) *NodeUpgradeInfoApplyConfiguration {
	b.IMUName = &value
	return b
}

// WithRetryCount sets the RetryCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryCount field is set to the value of the last call.
func (b *NodeUpgradeInfoApplyConfiguration) WithRetryCount(value int) *NodeUpgradeInfoApplyConfiguration {
	b.RetryCount = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *NodeUpgradeInfoApplyConfiguration) WithStartedAt(value string) *NodeUpgradeInfoApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithCompletedAt sets the CompletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedAt field is set to the value of the last call.
func (b *NodeUpgradeInfoApplyConfiguration) WithCompletedAt(value string) *NodeUpgradeInfoApplyConfiguration {
	b.CompletedAt = &value
	return b
}

// WithErrorMsg sets the ErrorMsg field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ErrorMsg field is set to the value of the last call.
func (b *NodeUpgradeInfoApplyConfiguration) WithErrorMsg(value string) *NodeUpgradeInfoApplyConfiguration {
	b.ErrorMsg = &value
	return b
}
