/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// NodeDataEngineResourcesApplyConfiguration represents a declarative configuration of the NodeDataEngineResources type for use
// with apply.
//
// NodeDataEngineResources overrides data engine resource settings on this node.
// Each nil field inherits the corresponding global setting.
type NodeDataEngineResourcesApplyConfiguration struct {
	V2 *NodeV2DataEngineResourcesApplyConfiguration `json:"v2,omitempty"`
}

// NodeDataEngineResourcesApplyConfiguration constructs a declarative configuration of the NodeDataEngineResources type for use with
// apply.
func NodeDataEngineResources() *NodeDataEngineResourcesApplyConfiguration {
	return &NodeDataEngineResourcesApplyConfiguration{}
}

// WithV2 sets the V2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V2 field is set to the value of the last call.
func (b *NodeDataEngineResourcesApplyConfiguration) WithV2(value *NodeV2DataEngineResourcesApplyConfiguration) *NodeDataEngineResourcesApplyConfiguration {
	b.V2 = value
	return b
}
