/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// PlannedDetachedReplicaApplyConfiguration represents a declarative configuration of the PlannedDetachedReplica type for use
// with apply.
//
// PlannedDetachedReplica records a backend that should be temporarily detached
// from an engine during an instance manager upgrade.
type PlannedDetachedReplicaApplyConfiguration struct {
	// Name is the replica name.
	Name *string `json:"name,omitempty"`
	// Address is the raw replica backend address recorded when the detach plan
	// is created.
	Address *string `json:"address,omitempty"`
}

// PlannedDetachedReplicaApplyConfiguration constructs a declarative configuration of the PlannedDetachedReplica type for use with
// apply.
func PlannedDetachedReplica() *PlannedDetachedReplicaApplyConfiguration {
	return &PlannedDetachedReplicaApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PlannedDetachedReplicaApplyConfiguration) WithName(value string) *PlannedDetachedReplicaApplyConfiguration {
	b.Name = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *PlannedDetachedReplicaApplyConfiguration) WithAddress(value string) *PlannedDetachedReplicaApplyConfiguration {
	b.Address = &value
	return b
}
