/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// RecurringJobStatusApplyConfiguration represents a declarative configuration of the RecurringJobStatus type for use
// with apply.
//
// RecurringJobStatus defines the observed state of the Longhorn recurring job
type RecurringJobStatusApplyConfiguration struct {
	// The owner ID which is responsible to reconcile this recurring job CR.
	OwnerID *string `json:"ownerID,omitempty"`
	// The number of jobs that have been triggered.
	ExecutionCount *int `json:"executionCount,omitempty"`
	// Records the outcome of the latest run of the recurring job.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RecurringJobStatusApplyConfiguration constructs a declarative configuration of the RecurringJobStatus type for use with
// apply.
func RecurringJobStatus() *RecurringJobStatusApplyConfiguration {
	return &RecurringJobStatusApplyConfiguration{}
}

// WithOwnerID sets the OwnerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerID field is set to the value of the last call.
func (b *RecurringJobStatusApplyConfiguration) WithOwnerID(value string) *RecurringJobStatusApplyConfiguration {
	b.OwnerID = &value
	return b
}

// WithExecutionCount sets the ExecutionCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExecutionCount field is set to the value of the last call.
func (b *RecurringJobStatusApplyConfiguration) WithExecutionCount(value int) *RecurringJobStatusApplyConfiguration {
	b.ExecutionCount = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RecurringJobStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *RecurringJobStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
