/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ReplicaRebuildStatisticsApplyConfiguration represents a declarative configuration of the ReplicaRebuildStatistics type for use
// with apply.
//
// ReplicaRebuildStatistics records how the snapshots were rebuilt in the last successful rebuild of the replica.
type ReplicaRebuildStatisticsApplyConfiguration struct {
	// The time when the last successful rebuild completed.
	RebuiltAt *string `json:"rebuiltAt,omitempty"`
	// The number of snapshots rebuilt by transferring the whole snapshot data.
	FullRebuildSnapshotCount *int `json:"fullRebuildSnapshotCount,omitempty"`
	// The number of snapshots rebuilt by reusing the existing snapshot data and transferring the differences only.
	DeltaRebuildSnapshotCount *int `json:"deltaRebuildSnapshotCount,omitempty"`
	// The number of snapshots rebuilt by skipping the data transfer since the existing snapshot is verified by checksum.
	FastRebuildSnapshotCount *int `json:"fastRebuildSnapshotCount,omitempty"`
}

// ReplicaRebuildStatisticsApplyConfiguration constructs a declarative configuration of the ReplicaRebuildStatistics type for use with
// apply.
func ReplicaRebuildStatistics() *ReplicaRebuildStatisticsApplyConfiguration {
	return &ReplicaRebuildStatisticsApplyConfiguration{}
}

// WithRebuiltAt sets the RebuiltAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RebuiltAt field is set to the value of the last call.
func (b *ReplicaRebuildStatisticsApplyConfiguration) WithRebuiltAt(value string) *ReplicaRebuildStatisticsApplyConfiguration {
	b.RebuiltAt = &value
	return b
}

// WithFullRebuildSnapshotCount sets the FullRebuildSnapshotCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullRebuildSnapshotCount field is set to the value of the last call.
func (b *ReplicaRebuildStatisticsApplyConfiguration) WithFullRebuildSnapshotCount(value int) *ReplicaRebuildStatisticsApplyConfiguration {
	b.FullRebuildSnapshotCount = &value
	return b
}

// WithDeltaRebuildSnapshotCount sets the DeltaRebuildSnapshotCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeltaRebuildSnapshotCount field is set to the value of the last call.
func (b *ReplicaRebuildStatisticsApplyConfiguration) WithDeltaRebuildSnapshotCount(value int) *ReplicaRebuildStatisticsApplyConfiguration {
	b.DeltaRebuildSnapshotCount = &value
	return b
}

// WithFastRebuildSnapshotCount sets the FastRebuildSnapshotCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FastRebuildSnapshotCount field is set to the value of the last call.
func (b *ReplicaRebuildStatisticsApplyConfiguration) WithFastRebuildSnapshotCount(value int) *ReplicaRebuildStatisticsApplyConfiguration {
	b.FastRebuildSnapshotCount = &value
	return b
}
