/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ReplicaSpecApplyConfiguration represents a declarative configuration of the ReplicaSpec type for use
// with apply.
//
// ReplicaSpec defines the desired state of the Longhorn replica
type ReplicaSpecApplyConfiguration struct {
	EngineName *string `json:"engineName,omitempty"`
	// MigrationEngineName is indicating the migrating engine which current connected to this replica. This is only
	// used for live migration of v2 data engine
	MigrationEngineName *string `json:"migrationEngineName,omitempty"`
	// HealthyAt is set the first time a replica becomes read/write in an engine after creation or rebuild. HealthyAt
	// indicates the time the last successful rebuild occurred. When HealthyAt is set, a replica is likely to have
	// useful (though possibly stale) data. HealthyAt is cleared before a rebuild. HealthyAt may be later than the
	// corresponding entry in an engine's replicaTransitionTimeMap because it is set when the volume controller
	// acknowledges the change.
	HealthyAt *string `json:"healthyAt,omitempty"`
	// LastHealthyAt is set every time a replica becomes read/write in an engine. Unlike HealthyAt, LastHealthyAt is
	// never cleared. LastHealthyAt is not a reliable indicator of the state of a replica's data. For example, a
	// replica with LastHealthyAt set may be in the middle of a rebuild. However, because it is never cleared, it can be
	// compared to LastFailedAt to help prevent dangerous replica deletion in some corner cases. LastHealthyAt may be
	// later than the corresponding entry in an engine's replicaTransitionTimeMap because it is set when the volume
	// controller acknowledges the change.
	LastHealthyAt *string `json:"lastHealthyAt,omitempty"`
	// FailedAt is set when a running replica fails or when a running engine is unable to use a replica for any reason.
	// FailedAt indicates the time the failure occurred. When FailedAt is set, a replica is likely to have useful
	// (though possibly stale) data. A replica with FailedAt set must be rebuilt from a non-failed replica (or it can
	// be used in a salvage if all replicas are failed). FailedAt is cleared before a rebuild or salvage. FailedAt may
	// be later than the corresponding entry in an engine's replicaTransitionTimeMap because it is set when the volume
	// controller acknowledges the change.
	FailedAt *string `json:"failedAt,omitempty"`
	// LastFailedAt is always set at the same time as FailedAt. Unlike FailedAt, LastFailedAt is never cleared.
	// LastFailedAt is not a reliable indicator of the state of a replica's data. For example, a replica with
	// LastFailedAt may already be healthy and in use again. However, because it is never cleared, it can be compared to
	// LastHealthyAt to help prevent dangerous replica deletion in some corner cases. LastFailedAt may be later than the
	// corresponding entry in an engine's replicaTransitionTimeMap because it is set when the volume controller
	// acknowledges the change.
	LastFailedAt                     *string `json:"lastFailedAt,omitempty"`
	DiskID                           *string `json:"diskID,omitempty"`
	DiskPath                         *string `json:"diskPath,omitempty"`
	DataDirectoryName                *string `json:"dataDirectoryName,omitempty"`
	BackingImage                     *string `json:"backingImage,omitempty"`
	Active                           *bool   `json:"active,omitempty"`
	HardNodeAffinity                 *string `json:"hardNodeAffinity,omitempty"`
	RevisionCounterDisabled          *bool   `json:"revisionCounterDisabled,omitempty"`
	UnmapMarkDiskChainRemovedEnabled *bool   `json:"unmapMarkDiskChainRemovedEnabled,omitempty"`
	RebuildRetryCount                *int    `json:"rebuildRetryCount,omitempty"`
	EvictionRequested                *bool   `json:"evictionRequested,omitempty"`
	SnapshotMaxCount                 *int    `json:"snapshotMaxCount,omitempty"`
	SnapshotMaxSize                  *int64  `json:"snapshotMaxSize,omitempty"`
}

// ReplicaSpecApplyConfiguration constructs a declarative configuration of the ReplicaSpec type for use with
// apply.
func ReplicaSpec() *ReplicaSpecApplyConfiguration {
	return &ReplicaSpecApplyConfiguration{}
}

// WithEngineName sets the EngineName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EngineName field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithEngineName(value string) *ReplicaSpecApplyConfiguration {
	b.EngineName = &value
	return b
}

// WithMigrationEngineName sets the MigrationEngineName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MigrationEngineName field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithMigrationEngineName(value string) *ReplicaSpecApplyConfiguration {
	b.MigrationEngineName = &value
	return b
}

// WithHealthyAt sets the HealthyAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthyAt field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithHealthyAt(value string) *ReplicaSpecApplyConfiguration {
	b.HealthyAt = &value
	return b
}

// WithLastHealthyAt sets the LastHealthyAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastHealthyAt field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithLastHealthyAt(value string) *ReplicaSpecApplyConfiguration {
	b.LastHealthyAt = &value
	return b
}

// WithFailedAt sets the FailedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedAt field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithFailedAt(value string) *ReplicaSpecApplyConfiguration {
	b.FailedAt = &value
	return b
}

// WithLastFailedAt sets the LastFailedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastFailedAt field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithLastFailedAt(value string) *ReplicaSpecApplyConfiguration {
	b.LastFailedAt = &value
	return b
}

// WithDiskID sets the DiskID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskID field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithDiskID(value string) *ReplicaSpecApplyConfiguration {
	b.DiskID = &value
	return b
}

// WithDiskPath sets the DiskPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskPath field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithDiskPath(value string) *ReplicaSpecApplyConfiguration {
	b.DiskPath = &value
	return b
}

// WithDataDirectoryName sets the DataDirectoryName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataDirectoryName field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithDataDirectoryName(value string) *ReplicaSpecApplyConfiguration {
	b.DataDirectoryName = &value
	return b
}

// WithBackingImage sets the BackingImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackingImage field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithBackingImage(value string) *ReplicaSpecApplyConfiguration {
	b.BackingImage = &value
	return b
}

// WithActive sets the Active field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Active field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithActive(value bool) *ReplicaSpecApplyConfiguration {
	b.Active = &value
	return b
}

// WithHardNodeAffinity sets the HardNodeAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HardNodeAffinity field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithHardNodeAffinity(value string) *ReplicaSpecApplyConfiguration {
	b.HardNodeAffinity = &value
	return b
}

// WithRevisionCounterDisabled sets the RevisionCounterDisabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RevisionCounterDisabled field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithRevisionCounterDisabled(value bool) *ReplicaSpecApplyConfiguration {
	b.RevisionCounterDisabled = &value
	return b
}

// WithUnmapMarkDiskChainRemovedEnabled sets the UnmapMarkDiskChainRemovedEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnmapMarkDiskChainRemovedEnabled field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithUnmapMarkDiskChainRemovedEnabled(value bool) *ReplicaSpecApplyConfiguration {
	b.UnmapMarkDiskChainRemovedEnabled = &value
	return b
}

// WithRebuildRetryCount sets the RebuildRetryCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RebuildRetryCount field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithRebuildRetryCount(value int) *ReplicaSpecApplyConfiguration {
	b.RebuildRetryCount = &value
	return b
}

// WithEvictionRequested sets the EvictionRequested field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvictionRequested field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithEvictionRequested(value bool) *ReplicaSpecApplyConfiguration {
	b.EvictionRequested = &value
	return b
}

// WithSnapshotMaxCount sets the SnapshotMaxCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotMaxCount field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithSnapshotMaxCount(value int) *ReplicaSpecApplyConfiguration {
	b.SnapshotMaxCount = &value
	return b
}

// WithSnapshotMaxSize sets the SnapshotMaxSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotMaxSize field is set to the value of the last call.
func (b *ReplicaSpecApplyConfiguration) WithSnapshotMaxSize(value int64) *ReplicaSpecApplyConfiguration {
	b.SnapshotMaxSize = &value
	return b
}
