/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ShardGroupSpecApplyConfiguration represents a declarative configuration of the ShardGroupSpec type for use
// with apply.
//
// ShardGroupSpec defines the desired state of the Longhorn ShardGroup
type ShardGroupSpecApplyConfiguration struct {
	// VolumeName is the name of the owning Volume CR. Immutable after creation.
	VolumeName *string `json:"volumeName,omitempty"`
	// DataChunks is the k parameter of the EC array. Immutable after creation.
	DataChunks *int `json:"dataChunks,omitempty"`
	// ParityChunks is the m parameter of the EC array. The ShardGroup tolerates up to m
	// simultaneous shard failures. Immutable after creation.
	ParityChunks *int `json:"parityChunks,omitempty"`
	// StripSizeKB is the EC chunk size in KiB. Must be a power of two in the range [4, 1024].
	// Immutable after creation.
	StripSizeKB *int `json:"stripSizeKB,omitempty"`
	// NodeID identifies the node hosting the long-lived ShardGroup process that owns the
	// EC volume's bdev_ec, lvol store, head lvol, and NVMe-oF export. It is typically equal
	// to Engine.Spec.NodeID for engine-process co-location. The Volume controller is the
	// sole writer and sets this field at first attach. NodeID is NOT cleared on volume
	// detach (the ShardGroup process keeps running across detach to preserve the lvstore
	// and head lvol on the encoded shard blocks for fast re-attach); it only changes on
	// engine-node failover or volume deletion.
	NodeID *string `json:"nodeID,omitempty"`
}

// ShardGroupSpecApplyConfiguration constructs a declarative configuration of the ShardGroupSpec type for use with
// apply.
func ShardGroupSpec() *ShardGroupSpecApplyConfiguration {
	return &ShardGroupSpecApplyConfiguration{}
}

// WithVolumeName sets the VolumeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeName field is set to the value of the last call.
func (b *ShardGroupSpecApplyConfiguration) WithVolumeName(value string) *ShardGroupSpecApplyConfiguration {
	b.VolumeName = &value
	return b
}

// WithDataChunks sets the DataChunks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataChunks field is set to the value of the last call.
func (b *ShardGroupSpecApplyConfiguration) WithDataChunks(value int) *ShardGroupSpecApplyConfiguration {
	b.DataChunks = &value
	return b
}

// WithParityChunks sets the ParityChunks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParityChunks field is set to the value of the last call.
func (b *ShardGroupSpecApplyConfiguration) WithParityChunks(value int) *ShardGroupSpecApplyConfiguration {
	b.ParityChunks = &value
	return b
}

// WithStripSizeKB sets the StripSizeKB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StripSizeKB field is set to the value of the last call.
func (b *ShardGroupSpecApplyConfiguration) WithStripSizeKB(value int) *ShardGroupSpecApplyConfiguration {
	b.StripSizeKB = &value
	return b
}

// WithNodeID sets the NodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeID field is set to the value of the last call.
func (b *ShardGroupSpecApplyConfiguration) WithNodeID(value string) *ShardGroupSpecApplyConfiguration {
	b.NodeID = &value
	return b
}
