/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// ShardGroupStatusApplyConfiguration represents a declarative configuration of the ShardGroupStatus type for use
// with apply.
//
// ShardGroupStatus defines the observed state of the Longhorn ShardGroup
type ShardGroupStatusApplyConfiguration struct {
	// OwnerID is the ID of the node that owns this ShardGroup.
	OwnerID *string `json:"ownerID,omitempty"`
	// State is the aggregate health state of the EC array.
	State *longhornv1beta2.ShardGroupState `json:"state,omitempty"`
	// FailedCount is the number of slots currently in the failed state. Slots being replaced
	// (ShardStateReplacing) are not counted; an active rebuild is tracked separately via
	// RebuildInProgress.
	FailedCount *int `json:"failedCount,omitempty"`
	// ShardRefs is an ordered list of Shard CR names, where the list index equals the EC slot index.
	ShardRefs []string `json:"shardRefs,omitempty"`
	// WIBDirtyRegion is the number of dirty WIB regions reported by the EC bdev.
	WIBDirtyRegion *int `json:"wibDirtyRegion,omitempty"`
	// ScrubInProgress indicates whether a background scrub is currently running.
	ScrubInProgress *bool `json:"scrubInProgress,omitempty"`
	// RebuildInProgress indicates whether a background shard rebuild is currently running.
	RebuildInProgress *bool `json:"rebuildInProgress,omitempty"`
	// GrowInProgress indicates whether a capacity expansion is currently running.
	GrowInProgress *bool `json:"growInProgress,omitempty"`
	// EvictingSlots is the ordered list of slot indices currently in the eviction
	// pipeline (old Shard CR deleted, replacement not yet rebuilt). Tracked in
	// status so VolumeEvictionController can observe progress without annotation parsing.
	EvictingSlots []int `json:"evictingSlots,omitempty"`
	// IntentionalDeleteSlots is the list of slot indices whose old Shard CR was
	// deleted intentionally (admin kubectl delete, eviction, drain). The replacement
	// Shard CR's failure-recovery debounce is bypassed for these slots so the
	// replace+rebuild sequence runs immediately rather than after the full
	// replica-replenishment-wait-interval. Cleared once the replacement reaches
	// ShardStateNormal with StorageIP set, and defensively cleared on ShardGroup
	// process re-bind.
	IntentionalDeleteSlots []int `json:"intentionalDeleteSlots,omitempty"`
	// ECShardAddressMap maps shard slot index (as string) to the NVMe-oF address ("ip:port")
	// of each healthy shard instance (ShardStateNormal with a non-empty StorageIP and Port).
	// It is the base-bdev list for the ShardGroup process's EC array, and acts as the readiness
	// gate (together with every Shard CR being in ShardStateNormal) before the ShardGroup
	// process is provisioned.
	ECShardAddressMap map[string]string `json:"ecShardAddressMap,omitempty"`
	// ProcessState is the runtime state of the ShardGroup process owned by this CR.
	ProcessState *longhornv1beta2.InstanceState `json:"processState,omitempty"`
	// StorageIP is the storage-network IP of the InstanceManager pod hosting the ShardGroup
	// process. Combined with Port and NQN, it forms the NVMe-oF endpoint that an EC volume's
	// engine attaches to.
	StorageIP *string `json:"storageIP,omitempty"`
	// Port is the NVMe-oF port allocated for the ShardGroup process's exposed head lvol.
	Port *int32 `json:"port,omitempty"`
	// NQN is the NVMe-oF subsystem NQN of the ShardGroup process's exposed head lvol.
	NQN *string `json:"nqn,omitempty"`
	// LvstoreUUID is reserved for the UUID of the lvol store created on bdev_ec inside the
	// ShardGroup process. It is currently unpopulated: the ShardGroup instance does not surface
	// the lvstore UUID over the instance-manager proto yet. Kept for forward-compatible
	// observability; not on the engine data path.
	LvstoreUUID *string `json:"lvstoreUUID,omitempty"`
	// HeadLvolUUID is the UUID of the head lvol on the ShardGroup-process-owned lvol
	// store. Surfaced for observability and debugging only.
	HeadLvolUUID *string `json:"headLvolUUID,omitempty"`
	// InstanceManagerName is the InstanceManager currently hosting the ShardGroup process,
	// set during provisioning and cleared on teardown. During a re-bind to a new node it may
	// still reference the previous InstanceManager until teardown completes, so consumers must
	// validate it against Spec.NodeID before trusting the endpoint above.
	InstanceManagerName *string `json:"instanceManagerName,omitempty"`
	// Conditions holds the latest observations of the ShardGroup's state, such as a
	// degraded read that returned EIO.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ShardGroupStatusApplyConfiguration constructs a declarative configuration of the ShardGroupStatus type for use with
// apply.
func ShardGroupStatus() *ShardGroupStatusApplyConfiguration {
	return &ShardGroupStatusApplyConfiguration{}
}

// WithOwnerID sets the OwnerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerID field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithOwnerID(value string) *ShardGroupStatusApplyConfiguration {
	b.OwnerID = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithState(value longhornv1beta2.ShardGroupState) *ShardGroupStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithFailedCount sets the FailedCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedCount field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithFailedCount(value int) *ShardGroupStatusApplyConfiguration {
	b.FailedCount = &value
	return b
}

// WithShardRefs adds the given value to the ShardRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ShardRefs field.
func (b *ShardGroupStatusApplyConfiguration) WithShardRefs(values ...string) *ShardGroupStatusApplyConfiguration {
	for i := range values {
		b.ShardRefs = append(b.ShardRefs, values[i])
	}
	return b
}

// WithWIBDirtyRegion sets the WIBDirtyRegion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WIBDirtyRegion field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithWIBDirtyRegion(value int) *ShardGroupStatusApplyConfiguration {
	b.WIBDirtyRegion = &value
	return b
}

// WithScrubInProgress sets the ScrubInProgress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScrubInProgress field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithScrubInProgress(value bool) *ShardGroupStatusApplyConfiguration {
	b.ScrubInProgress = &value
	return b
}

// WithRebuildInProgress sets the RebuildInProgress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RebuildInProgress field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithRebuildInProgress(value bool) *ShardGroupStatusApplyConfiguration {
	b.RebuildInProgress = &value
	return b
}

// WithGrowInProgress sets the GrowInProgress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrowInProgress field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithGrowInProgress(value bool) *ShardGroupStatusApplyConfiguration {
	b.GrowInProgress = &value
	return b
}

// WithEvictingSlots adds the given value to the EvictingSlots field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EvictingSlots field.
func (b *ShardGroupStatusApplyConfiguration) WithEvictingSlots(values ...int) *ShardGroupStatusApplyConfiguration {
	for i := range values {
		b.EvictingSlots = append(b.EvictingSlots, values[i])
	}
	return b
}

// WithIntentionalDeleteSlots adds the given value to the IntentionalDeleteSlots field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IntentionalDeleteSlots field.
func (b *ShardGroupStatusApplyConfiguration) WithIntentionalDeleteSlots(values ...int) *ShardGroupStatusApplyConfiguration {
	for i := range values {
		b.IntentionalDeleteSlots = append(b.IntentionalDeleteSlots, values[i])
	}
	return b
}

// WithECShardAddressMap puts the entries into the ECShardAddressMap field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ECShardAddressMap field,
// overwriting an existing map entries in ECShardAddressMap field with the same key.
func (b *ShardGroupStatusApplyConfiguration) WithECShardAddressMap(entries map[string]string) *ShardGroupStatusApplyConfiguration {
	if b.ECShardAddressMap == nil && len(entries) > 0 {
		b.ECShardAddressMap = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ECShardAddressMap[k] = v
	}
	return b
}

// WithProcessState sets the ProcessState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcessState field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithProcessState(value longhornv1beta2.InstanceState) *ShardGroupStatusApplyConfiguration {
	b.ProcessState = &value
	return b
}

// WithStorageIP sets the StorageIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageIP field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithStorageIP(value string) *ShardGroupStatusApplyConfiguration {
	b.StorageIP = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithPort(value int32) *ShardGroupStatusApplyConfiguration {
	b.Port = &value
	return b
}

// WithNQN sets the NQN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NQN field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithNQN(value string) *ShardGroupStatusApplyConfiguration {
	b.NQN = &value
	return b
}

// WithLvstoreUUID sets the LvstoreUUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LvstoreUUID field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithLvstoreUUID(value string) *ShardGroupStatusApplyConfiguration {
	b.LvstoreUUID = &value
	return b
}

// WithHeadLvolUUID sets the HeadLvolUUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeadLvolUUID field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithHeadLvolUUID(value string) *ShardGroupStatusApplyConfiguration {
	b.HeadLvolUUID = &value
	return b
}

// WithInstanceManagerName sets the InstanceManagerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceManagerName field is set to the value of the last call.
func (b *ShardGroupStatusApplyConfiguration) WithInstanceManagerName(value string) *ShardGroupStatusApplyConfiguration {
	b.InstanceManagerName = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ShardGroupStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *ShardGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
