/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// ShardStatusApplyConfiguration represents a declarative configuration of the ShardStatus type for use
// with apply.
//
// ShardStatus defines the observed state of the Longhorn Shard
type ShardStatusApplyConfiguration struct {
	// OwnerID is the ID of the node that owns this Shard.
	OwnerID *string `json:"ownerID,omitempty"`
	// State is the health state of this EC shard slot.
	State *longhornv1beta2.ShardState `json:"state,omitempty"`
	// Role is the EC role of this slot (data or parity). Derived from SlotIndex and the parent
	// ShardGroup's DataChunks; stored here for informational purposes only.
	Role *longhornv1beta2.ShardRole `json:"role,omitempty"`
	// StorageIP is the IP address of the NVMe-oF target exported by the shard's InstanceManager.
	// Populated after the shard instance is running.
	StorageIP *string `json:"storageIP,omitempty"`
	// Port is the NVMe-oF port of the shard's target export.
	Port *int32 `json:"port,omitempty"`
	// RebuildProgress is the rebuild completion percentage (0-100).
	RebuildProgress *int `json:"rebuildProgress,omitempty"`
	// LastFailureTimestamp is the RFC3339 timestamp of the most recent shard failure.
	LastFailureTimestamp *string `json:"lastFailureTimestamp,omitempty"`
	// ReplaceTriggered is set to true after shard replacement has been initiated, to prevent
	// re-issuing the replace command on subsequent cycles while SPDK advances the slot state.
	// Cleared when the slot state transitions away from Failed.
	ReplaceTriggered *bool `json:"replaceTriggered,omitempty"`
}

// ShardStatusApplyConfiguration constructs a declarative configuration of the ShardStatus type for use with
// apply.
func ShardStatus() *ShardStatusApplyConfiguration {
	return &ShardStatusApplyConfiguration{}
}

// WithOwnerID sets the OwnerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerID field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithOwnerID(value string) *ShardStatusApplyConfiguration {
	b.OwnerID = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithState(value longhornv1beta2.ShardState) *ShardStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithRole(value longhornv1beta2.ShardRole) *ShardStatusApplyConfiguration {
	b.Role = &value
	return b
}

// WithStorageIP sets the StorageIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageIP field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithStorageIP(value string) *ShardStatusApplyConfiguration {
	b.StorageIP = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithPort(value int32) *ShardStatusApplyConfiguration {
	b.Port = &value
	return b
}

// WithRebuildProgress sets the RebuildProgress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RebuildProgress field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithRebuildProgress(value int) *ShardStatusApplyConfiguration {
	b.RebuildProgress = &value
	return b
}

// WithLastFailureTimestamp sets the LastFailureTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastFailureTimestamp field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithLastFailureTimestamp(value string) *ShardStatusApplyConfiguration {
	b.LastFailureTimestamp = &value
	return b
}

// WithReplaceTriggered sets the ReplaceTriggered field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplaceTriggered field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithReplaceTriggered(value bool) *ShardStatusApplyConfiguration {
	b.ReplaceTriggered = &value
	return b
}
