/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ShardSpecApplyConfiguration represents a declarative configuration of the ShardSpec type for use
// with apply.
//
// ShardSpec defines the desired state of the Longhorn Shard
type ShardSpecApplyConfiguration struct {
	// ShardGroupName is the name of the owning ShardGroup CR. Immutable after creation.
	ShardGroupName *string `json:"shardGroupName,omitempty"`
	// SlotIndex is the zero-based position of this shard in the EC base-bdev array.
	// Determines the shard's role: indices 0..k-1 are DATA, k..k+m-1 are PARITY.
	// Immutable after creation.
	SlotIndex *int `json:"slotIndex,omitempty"`
	// Size is the shard lvol size in bytes. Set by the ShardGroup controller at creation time
	// and used for idempotent reconciliation.
	Size *int64 `json:"size,omitempty"`
	// NodeID is the node where this shard's lvol resides and its NVMe-oF target runs.
	NodeID *string `json:"nodeID,omitempty"`
	// DiskPath is the path of the disk that hosts the shard lvol.
	DiskPath *string `json:"diskPath,omitempty"`
	// DiskUUID is the UUID of the disk that hosts the shard lvol.
	DiskUUID *string `json:"diskUUID,omitempty"`
	// EvictionRequested indicates this shard should be relocated to a different node or disk.
	// Set by the node controller when the shard's node is being drained or its disk is evicted.
	EvictionRequested *bool `json:"evictionRequested,omitempty"`
}

// ShardSpecApplyConfiguration constructs a declarative configuration of the ShardSpec type for use with
// apply.
func ShardSpec() *ShardSpecApplyConfiguration {
	return &ShardSpecApplyConfiguration{}
}

// WithShardGroupName sets the ShardGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShardGroupName field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithShardGroupName(value string) *ShardSpecApplyConfiguration {
	b.ShardGroupName = &value
	return b
}

// WithSlotIndex sets the SlotIndex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SlotIndex field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithSlotIndex(value int) *ShardSpecApplyConfiguration {
	b.SlotIndex = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithSize(value int64) *ShardSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithNodeID sets the NodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeID field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithNodeID(value string) *ShardSpecApplyConfiguration {
	b.NodeID = &value
	return b
}

// WithDiskPath sets the DiskPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskPath field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithDiskPath(value string) *ShardSpecApplyConfiguration {
	b.DiskPath = &value
	return b
}

// WithDiskUUID sets the DiskUUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskUUID field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithDiskUUID(value string) *ShardSpecApplyConfiguration {
	b.DiskUUID = &value
	return b
}

// WithEvictionRequested sets the EvictionRequested field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvictionRequested field is set to the value of the last call.
func (b *ShardSpecApplyConfiguration) WithEvictionRequested(value bool) *ShardSpecApplyConfiguration {
	b.EvictionRequested = &value
	return b
}
