/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SnapshotGroupSpecApplyConfiguration represents a declarative configuration of the SnapshotGroupSpec type for use
// with apply.
//
// SnapshotGroupSpec defines the desired state of the Longhorn SnapshotGroup.
// The whole spec is immutable after creation: a group is a point-in-time
// request, so changing members later has no meaning.
type SnapshotGroupSpecApplyConfiguration struct {
	// Volumes explicitly lists the member volumes. Exactly one of Volumes or
	// VolumeSelector may be set at creation; the mutating webhook resolves the
	// selection into Members at admission.
	Volumes []string `json:"volumes,omitempty"`
	// VolumeSelector selects the member volumes by their labels. Exactly one of
	// Volumes or VolumeSelector may be set at creation.
	VolumeSelector *v1.LabelSelectorApplyConfiguration `json:"volumeSelector,omitempty"`
	// Labels are engine snapshot labels applied to every member (Snapshot
	// spec.labels). They are not visible to Kubernetes label selectors.
	// Reserved recurring-job label keys are rejected at admission.
	Labels map[string]string `json:"labels,omitempty"`
	// DeadlineSeconds is the deadline for taking every member snapshot,
	// measured from the group's metadata.creationTimestamp. Stamped by the
	// mutating webhook when unset (default 300, valid range 10 to 3600).
	DeadlineSeconds *int64 `json:"deadlineSeconds,omitempty"`
	// Members is the fixed member set, resolved from Volumes or VolumeSelector
	// and stamped by the mutating webhook at admission. It may not be set by
	// the user.
	Members []SnapshotGroupMemberApplyConfiguration `json:"members,omitempty"`
}

// SnapshotGroupSpecApplyConfiguration constructs a declarative configuration of the SnapshotGroupSpec type for use with
// apply.
func SnapshotGroupSpec() *SnapshotGroupSpecApplyConfiguration {
	return &SnapshotGroupSpecApplyConfiguration{}
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *SnapshotGroupSpecApplyConfiguration) WithVolumes(values ...string) *SnapshotGroupSpecApplyConfiguration {
	for i := range values {
		b.Volumes = append(b.Volumes, values[i])
	}
	return b
}

// WithVolumeSelector sets the VolumeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeSelector field is set to the value of the last call.
func (b *SnapshotGroupSpecApplyConfiguration) WithVolumeSelector(value *v1.LabelSelectorApplyConfiguration) *SnapshotGroupSpecApplyConfiguration {
	b.VolumeSelector = value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *SnapshotGroupSpecApplyConfiguration) WithLabels(entries map[string]string) *SnapshotGroupSpecApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithDeadlineSeconds sets the DeadlineSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeadlineSeconds field is set to the value of the last call.
func (b *SnapshotGroupSpecApplyConfiguration) WithDeadlineSeconds(value int64) *SnapshotGroupSpecApplyConfiguration {
	b.DeadlineSeconds = &value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *SnapshotGroupSpecApplyConfiguration) WithMembers(values ...*SnapshotGroupMemberApplyConfiguration) *SnapshotGroupSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembers")
		}
		b.Members = append(b.Members, *values[i])
	}
	return b
}
