/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// SnapshotGroupStatusApplyConfiguration represents a declarative configuration of the SnapshotGroupStatus type for use
// with apply.
//
// SnapshotGroupStatus defines the observed state of the Longhorn SnapshotGroup
type SnapshotGroupStatusApplyConfiguration struct {
	// OwnerID is the ID of the node that owns this SnapshotGroup.
	OwnerID *string `json:"ownerID,omitempty"`
	// Phase is the lifecycle phase: empty until the first reconcile, then
	// InProgress -> Ready | Failed.
	Phase *longhornv1beta2.SnapshotGroupPhase `json:"phase,omitempty"`
	// Members is the observed state of every member, one entry per spec
	// member. It is the primary debugging signal: each entry carries the
	// member's last error and creation time.
	Members []SnapshotGroupMemberStatusApplyConfiguration `json:"members,omitempty"`
	// ReadyToUse is true exactly when Phase is Ready, so a failed, partial, or
	// empty group is never reported ready. It stays true on a Degraded group:
	// the set was validly taken and its surviving members remain individually
	// restorable, while the Degraded condition answers whether the set is
	// still complete.
	ReadyToUse *bool `json:"readyToUse,omitempty"`
	// CreationTime is the latest member creation time, set when the group
	// becomes Ready.
	CreationTime *string `json:"creationTime,omitempty"`
	// Error is set when the group fails (deadline, name collision).
	Error *string `json:"error,omitempty"`
	// Conditions holds the latest observations of the SnapshotGroup's state,
	// such as Degraded.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// SnapshotGroupStatusApplyConfiguration constructs a declarative configuration of the SnapshotGroupStatus type for use with
// apply.
func SnapshotGroupStatus() *SnapshotGroupStatusApplyConfiguration {
	return &SnapshotGroupStatusApplyConfiguration{}
}

// WithOwnerID sets the OwnerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerID field is set to the value of the last call.
func (b *SnapshotGroupStatusApplyConfiguration) WithOwnerID(value string) *SnapshotGroupStatusApplyConfiguration {
	b.OwnerID = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *SnapshotGroupStatusApplyConfiguration) WithPhase(value longhornv1beta2.SnapshotGroupPhase) *SnapshotGroupStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *SnapshotGroupStatusApplyConfiguration) WithMembers(values ...*SnapshotGroupMemberStatusApplyConfiguration) *SnapshotGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembers")
		}
		b.Members = append(b.Members, *values[i])
	}
	return b
}

// WithReadyToUse sets the ReadyToUse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyToUse field is set to the value of the last call.
func (b *SnapshotGroupStatusApplyConfiguration) WithReadyToUse(value bool) *SnapshotGroupStatusApplyConfiguration {
	b.ReadyToUse = &value
	return b
}

// WithCreationTime sets the CreationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTime field is set to the value of the last call.
func (b *SnapshotGroupStatusApplyConfiguration) WithCreationTime(value string) *SnapshotGroupStatusApplyConfiguration {
	b.CreationTime = &value
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *SnapshotGroupStatusApplyConfiguration) WithError(value string) *SnapshotGroupStatusApplyConfiguration {
	b.Error = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SnapshotGroupStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *SnapshotGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
