/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// SnapshotGroupMemberStatusApplyConfiguration represents a declarative configuration of the SnapshotGroupMemberStatus type for use
// with apply.
//
// SnapshotGroupMemberStatus is the observed state of one member, mirrored from
// its Snapshot CR.
type SnapshotGroupMemberStatusApplyConfiguration struct {
	VolumeName   *string `json:"volumeName,omitempty"`
	SnapshotName *string `json:"snapshotName,omitempty"`
	// ReadyToUse mirrors the member Snapshot while the group is InProgress.
	// After the group is Ready, a member later deleted or unusable is recorded
	// here as false: member entries always tell the per-member truth.
	ReadyToUse *bool `json:"readyToUse,omitempty"`
	// CreationTime is the engine snapshot creation time, mirrored from the
	// member Snapshot. It is kept when the member is later lost.
	CreationTime *string `json:"creationTime,omitempty"`
	// Error is the last member error. A member Snapshot CR that disappeared
	// after the group became Ready is recorded with the synthetic error
	// "member snapshot deleted"; an unusable member keeps its own mirrored
	// error.
	Error *string `json:"error,omitempty"`
}

// SnapshotGroupMemberStatusApplyConfiguration constructs a declarative configuration of the SnapshotGroupMemberStatus type for use with
// apply.
func SnapshotGroupMemberStatus() *SnapshotGroupMemberStatusApplyConfiguration {
	return &SnapshotGroupMemberStatusApplyConfiguration{}
}

// WithVolumeName sets the VolumeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeName field is set to the value of the last call.
func (b *SnapshotGroupMemberStatusApplyConfiguration) WithVolumeName(value string) *SnapshotGroupMemberStatusApplyConfiguration {
	b.VolumeName = &value
	return b
}

// WithSnapshotName sets the SnapshotName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotName field is set to the value of the last call.
func (b *SnapshotGroupMemberStatusApplyConfiguration) WithSnapshotName(value string) *SnapshotGroupMemberStatusApplyConfiguration {
	b.SnapshotName = &value
	return b
}

// WithReadyToUse sets the ReadyToUse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyToUse field is set to the value of the last call.
func (b *SnapshotGroupMemberStatusApplyConfiguration) WithReadyToUse(value bool) *SnapshotGroupMemberStatusApplyConfiguration {
	b.ReadyToUse = &value
	return b
}

// WithCreationTime sets the CreationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTime field is set to the value of the last call.
func (b *SnapshotGroupMemberStatusApplyConfiguration) WithCreationTime(value string) *SnapshotGroupMemberStatusApplyConfiguration {
	b.CreationTime = &value
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *SnapshotGroupMemberStatusApplyConfiguration) WithError(value string) *SnapshotGroupMemberStatusApplyConfiguration {
	b.Error = &value
	return b
}
