/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// V2DataEngineStatusApplyConfiguration represents a declarative configuration of the V2DataEngineStatus type for use
// with apply.
type V2DataEngineStatusApplyConfiguration struct {
	CPUMask       *string `json:"cpuMask,omitempty"`
	CPUCoreNumber *int64  `json:"cpuCoreNumber,omitempty"`
	// InterruptModeEnabled indicates whether the V2 data engine is running in
	// interrupt mode (true) or polling mode (false). Set by Longhorn manager;
	// read-only to users.
	InterruptModeEnabled *string `json:"interruptModeEnabled,omitempty"`
	// Applied node effective values (node spec override or global setting) as of
	// the last pod creation; nil until this manager version has created the pod.
	// Set by Longhorn manager; read-only to users.
	MemorySizeMiB      *int64 `json:"memorySizeMiB,omitempty"`
	HugepageEnabled    *bool  `json:"hugepageEnabled,omitempty"`
	IobufSmallPoolSize *int64 `json:"iobufSmallPoolSize,omitempty"`
	IobufLargePoolSize *int64 `json:"iobufLargePoolSize,omitempty"`
}

// V2DataEngineStatusApplyConfiguration constructs a declarative configuration of the V2DataEngineStatus type for use with
// apply.
func V2DataEngineStatus() *V2DataEngineStatusApplyConfiguration {
	return &V2DataEngineStatusApplyConfiguration{}
}

// WithCPUMask sets the CPUMask field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPUMask field is set to the value of the last call.
func (b *V2DataEngineStatusApplyConfiguration) WithCPUMask(value string) *V2DataEngineStatusApplyConfiguration {
	b.CPUMask = &value
	return b
}

// WithCPUCoreNumber sets the CPUCoreNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPUCoreNumber field is set to the value of the last call.
func (b *V2DataEngineStatusApplyConfiguration) WithCPUCoreNumber(value int64) *V2DataEngineStatusApplyConfiguration {
	b.CPUCoreNumber = &value
	return b
}

// WithInterruptModeEnabled sets the InterruptModeEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InterruptModeEnabled field is set to the value of the last call.
func (b *V2DataEngineStatusApplyConfiguration) WithInterruptModeEnabled(value string) *V2DataEngineStatusApplyConfiguration {
	b.InterruptModeEnabled = &value
	return b
}

// WithMemorySizeMiB sets the MemorySizeMiB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemorySizeMiB field is set to the value of the last call.
func (b *V2DataEngineStatusApplyConfiguration) WithMemorySizeMiB(value int64) *V2DataEngineStatusApplyConfiguration {
	b.MemorySizeMiB = &value
	return b
}

// WithHugepageEnabled sets the HugepageEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HugepageEnabled field is set to the value of the last call.
func (b *V2DataEngineStatusApplyConfiguration) WithHugepageEnabled(value bool) *V2DataEngineStatusApplyConfiguration {
	b.HugepageEnabled = &value
	return b
}

// WithIobufSmallPoolSize sets the IobufSmallPoolSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IobufSmallPoolSize field is set to the value of the last call.
func (b *V2DataEngineStatusApplyConfiguration) WithIobufSmallPoolSize(value int64) *V2DataEngineStatusApplyConfiguration {
	b.IobufSmallPoolSize = &value
	return b
}

// WithIobufLargePoolSize sets the IobufLargePoolSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IobufLargePoolSize field is set to the value of the last call.
func (b *V2DataEngineStatusApplyConfiguration) WithIobufLargePoolSize(value int64) *V2DataEngineStatusApplyConfiguration {
	b.IobufLargePoolSize = &value
	return b
}
