/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// VolumeDataLayoutApplyConfiguration represents a declarative configuration of the VolumeDataLayout type for use
// with apply.
//
// VolumeDataLayout declares the user's intended data layout for the volume. The entire struct is
// immutable after creation. EC sub-fields are only meaningful when Type is VolumeDataLayoutTypeSharded.
type VolumeDataLayoutApplyConfiguration struct {
	// Type describes how volume data is distributed across nodes.
	Type *longhornv1beta2.VolumeDataLayoutType `json:"type,omitempty"`
	// Mode describes the specific data protection mechanism in use.
	// Empty for V1 volumes where no SPDK-level mode applies.
	Mode *longhornv1beta2.VolumeDataLayoutMode `json:"mode,omitempty"`
	// DataChunks is the number of data chunks (k) in the EC array.
	// Required when Type is sharded; must be 0 for replicated volumes.
	DataChunks *int `json:"dataChunks,omitempty"`
	// ParityChunks is the number of parity chunks (m) in the EC array.
	// The volume tolerates up to m simultaneous disk failures.
	// Required when Type is sharded; must be 0 for replicated volumes.
	ParityChunks *int `json:"parityChunks,omitempty"`
	// StripSizeKB is the chunk size in KiB used by the EC bdev.
	// Must be a power of two in the range [4, 1024].
	// Required when Type is sharded; must be 0 for replicated volumes.
	StripSizeKB *int `json:"stripSizeKB,omitempty"`
}

// VolumeDataLayoutApplyConfiguration constructs a declarative configuration of the VolumeDataLayout type for use with
// apply.
func VolumeDataLayout() *VolumeDataLayoutApplyConfiguration {
	return &VolumeDataLayoutApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *VolumeDataLayoutApplyConfiguration) WithType(value longhornv1beta2.VolumeDataLayoutType) *VolumeDataLayoutApplyConfiguration {
	b.Type = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *VolumeDataLayoutApplyConfiguration) WithMode(value longhornv1beta2.VolumeDataLayoutMode) *VolumeDataLayoutApplyConfiguration {
	b.Mode = &value
	return b
}

// WithDataChunks sets the DataChunks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataChunks field is set to the value of the last call.
func (b *VolumeDataLayoutApplyConfiguration) WithDataChunks(value int) *VolumeDataLayoutApplyConfiguration {
	b.DataChunks = &value
	return b
}

// WithParityChunks sets the ParityChunks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParityChunks field is set to the value of the last call.
func (b *VolumeDataLayoutApplyConfiguration) WithParityChunks(value int) *VolumeDataLayoutApplyConfiguration {
	b.ParityChunks = &value
	return b
}

// WithStripSizeKB sets the StripSizeKB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StripSizeKB field is set to the value of the last call.
func (b *VolumeDataLayoutApplyConfiguration) WithStripSizeKB(value int) *VolumeDataLayoutApplyConfiguration {
	b.StripSizeKB = &value
	return b
}
