/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// VolumeTopologyTermApplyConfiguration represents a declarative configuration of the VolumeTopologyTerm type for use
// with apply.
//
// VolumeTopologyTerm is one failure domain a volume's replicas may be
// scheduled in. A node satisfies the term when its zone and region match the
// non-empty fields.
type VolumeTopologyTermApplyConfiguration struct {
	Zone   *string `json:"zone,omitempty"`
	Region *string `json:"region,omitempty"`
}

// VolumeTopologyTermApplyConfiguration constructs a declarative configuration of the VolumeTopologyTerm type for use with
// apply.
func VolumeTopologyTerm() *VolumeTopologyTermApplyConfiguration {
	return &VolumeTopologyTermApplyConfiguration{}
}

// WithZone sets the Zone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Zone field is set to the value of the last call.
func (b *VolumeTopologyTermApplyConfiguration) WithZone(value string) *VolumeTopologyTermApplyConfiguration {
	b.Zone = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *VolumeTopologyTermApplyConfiguration) WithRegion(value string) *VolumeTopologyTermApplyConfiguration {
	b.Region = &value
	return b
}
