/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// VolumeAntiAffinityApplyConfiguration represents a declarative configuration of the VolumeAntiAffinity type for use
// with apply.
//
// VolumeAntiAffinity keeps a volume's replicas away from the storage nodes that
// hold replicas of related volumes. Labels identify this volume to other
// volumes' selectors; Selectors pick the volumes this one avoids. The
// preference is soft and evaluated only when a replica is newly placed.
type VolumeAntiAffinityApplyConfiguration struct {
	Labels    map[string]string                    `json:"labels,omitempty"`
	Selectors []v1.LabelSelectorApplyConfiguration `json:"selectors,omitempty"`
	// PendingInheritance holds replica scheduling until the anti-affinity has
	// been derived from the pod using the volume. Set by the CSI driver at
	// creation and cleared once the PV is bound.
	PendingInheritance *bool `json:"pendingInheritance,omitempty"`
}

// VolumeAntiAffinityApplyConfiguration constructs a declarative configuration of the VolumeAntiAffinity type for use with
// apply.
func VolumeAntiAffinity() *VolumeAntiAffinityApplyConfiguration {
	return &VolumeAntiAffinityApplyConfiguration{}
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *VolumeAntiAffinityApplyConfiguration) WithLabels(entries map[string]string) *VolumeAntiAffinityApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithSelectors adds the given value to the Selectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Selectors field.
func (b *VolumeAntiAffinityApplyConfiguration) WithSelectors(values ...*v1.LabelSelectorApplyConfiguration) *VolumeAntiAffinityApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSelectors")
		}
		b.Selectors = append(b.Selectors, *values[i])
	}
	return b
}

// WithPendingInheritance sets the PendingInheritance field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PendingInheritance field is set to the value of the last call.
func (b *VolumeAntiAffinityApplyConfiguration) WithPendingInheritance(value bool) *VolumeAntiAffinityApplyConfiguration {
	b.PendingInheritance = &value
	return b
}
