apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: volume-cronjob-job1
  namespace: longhorn-system
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: init-container
            image: rancher/longhorn-engine:8c8289f
            command: ['sh', '-c', 'cp /usr/local/bin/* /data/']
            volumeMounts:
            - name: execbin
              mountPath: /data/
          containers:
          - name: longhorn-manager
            image: yasker/longhorn-manager:0073002-dirty
            imagePullPolicy: Always
            securityContext:
              privileged: true
            command: ["longhorn-manager", "-d",
                    "snapshot", "test",
                    "--snapshot-name", "testsnap",
                    "--retain", "5",
                    "--labels", "recurringjob=job1",
                    "--backuptarget", "nfs://longhorn-test-nfs-svc.default:/opt/backupstore"]
            volumeMounts:
            - name: execbin
              mountPath: /usr/local/bin/
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumes:
          - name: execbin
            emptyDir: {}
          serviceAccountName: longhorn-service-account
          restartPolicy: OnFailure
