apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: longhorn-flexvolume-driver-deployer
  namespace: longhorn-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: longhorn-flexvolume-driver-deployer
    spec:
      containers:
        - name: longhorn-flexvolume-driver-deployer
          image: rancher/longhorn-manager:a2c283a
          imagePullPolicy: Always
          command:
          - longhorn-manager
          - -d
          - deploy-flexvolume-driver
          - --manager-image
          - rancher/longhorn-manager:a2c283a
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      serviceAccountName: longhorn-service-account
