apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: longhorn-flexvolume-driver-deployer
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-flexvolume-driver-deployer
  template:
    metadata:
      labels:
        app: longhorn-flexvolume-driver-deployer
    spec:
      containers:
        - name: longhorn-flexvolume-driver-deployer
          image: rancher/longhorn-manager:d5227ec
          imagePullPolicy: Always
          command:
          - longhorn-manager
          - -d
          - deploy-flexvolume-driver
          - --manager-image
          - rancher/longhorn-manager:d5227ec
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FLEXVOLUME_DIR
            # FOR RKE
            value: "/var/lib/kubelet/volumeplugins"
            # FOR GKE
            #value: "/home/kubernetes/flexvolume/"
            # For default or auto detection with Kubernetes <= v1.9
            #value: ""
      serviceAccountName: longhorn-service-account
