apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: longhorn-driver
  namespace: longhorn-system
spec:
  template:
    metadata:
      name: longhorn-driver
      labels:
        app: longhorn-driver
    spec:
      containers:
        - name: longhorn-driver-container
          image: rancher/longhorn-manager:c5c02b9
          imagePullPolicy: Always
          command: ["/entrypoint.sh"]
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-longhorn-mount
            - mountPath: /binmnt
              name: usr-local-bin-mount
            - name: host-proc-mount
              mountPath: /host/proc/
          env:
            - name: LONGHORN_BACKEND_SVC
              value: "longhorn-backend"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: usr-local-bin-mount
          hostPath:
            path: /usr/local/bin/
        - name: host-proc-mount
          hostPath:
            path: /proc/
        - name: flexvolume-longhorn-mount
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
            #FOR GKE
            #path: /home/kubernetes/flexvolume/
