apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: longhorn-driver-deployer
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-driver-deployer
  template:
    metadata:
      labels:
        app: longhorn-driver-deployer
    spec:
      initContainers:
        - name: wait-longhorn-manager
          image: rancher/longhorn-manager:9b29b88
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1) != "200" ]; do echo waiting; sleep 2; done']
      containers:
        - name: longhorn-driver-deployer
          image: rancher/longhorn-manager:9b29b88
          imagePullPolicy: Always
          command:
          - longhorn-manager
          - -d
          - deploy-driver
          - --manager-image
          - rancher/longhorn-manager:9b29b88
          - --manager-url
          - http://longhorn-backend:9500/v1
          # manually choose "flexvolume" or "csi"
          #- --driver
          #- flexvolume
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: FLEXVOLUME_DIR
            # FOR RKE
            value: "/var/lib/kubelet/volumeplugins"
            # FOR GKE
            #value: "/home/kubernetes/flexvolume/"
            # For default or auto detection with Kubernetes <= v1.8
            #value: ""
      serviceAccountName: longhorn-service-account
