pull_request_rules:
- name: Automatically merge PRs
  conditions:
  - check-success="Build binaries"
  - "#approved-reviews-by>=2"
  - approved-reviews-by=@longhorn/maintainer
  actions:
    merge:
      method: rebase

- name: Automatically merge Renovate PRs
  conditions:
  - check-success="Build binaries"
  - author = renovate[bot]
  actions:
    merge:
      method: rebase

- name: ask to resolve conflict
  conditions:
  - conflict
  actions:
    comment:
      message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏

# Comment on the PR to trigger backport. ex: @Mergifyio copy stable/3.1 stable/4.0
- name: backport patches to stable branch
  conditions:
  - base=master
  actions:
    backport:
      title: "[BACKPORT][{{ destination_branch }}] {{ title }}"
      body: |
        This is an automatic backport of pull request #{{number}}.

        {{cherry_pick_error}}
      assignees:
      - "{{ author }}"
