---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: publish-master-image
  image: plugins/docker
  settings:
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-manager
    tag: master
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

- name: publish-tagged-image
  image: plugins/docker
  settings:
    build_args:
      - "VERSION=${DRONE_TAG}"
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-manager
    tag: "${DRONE_TAG}"
    username:
      from_secret: docker_username
  when:
    branch:
    - drone-test
    event:
    - tag

- name: slack_notify
  image: plugins/slack
  settings:
    template: "Build {{build.link}} failed.\n"
    username: Drone_Publish
    webhook:
      from_secret: slack_webhook
  when:
    event:
      exclude:
      - pull_request
    instance:
      include:
      - drone-publish.rancher.io
    status:
      - failure

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
