/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	context "context"

	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	applyconfigurationlonghornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/client/applyconfiguration/longhorn/v1beta2"
	scheme "github.com/longhorn/longhorn-manager/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DiskSchedulesGetter has a method to return a DiskScheduleInterface.
// A group's client should implement this interface.
type DiskSchedulesGetter interface {
	DiskSchedules(namespace string) DiskScheduleInterface
}

// DiskScheduleInterface has methods to work with DiskSchedule resources.
type DiskScheduleInterface interface {
	Create(ctx context.Context, diskSchedule *longhornv1beta2.DiskSchedule, opts v1.CreateOptions) (*longhornv1beta2.DiskSchedule, error)
	Update(ctx context.Context, diskSchedule *longhornv1beta2.DiskSchedule, opts v1.UpdateOptions) (*longhornv1beta2.DiskSchedule, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, diskSchedule *longhornv1beta2.DiskSchedule, opts v1.UpdateOptions) (*longhornv1beta2.DiskSchedule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*longhornv1beta2.DiskSchedule, error)
	List(ctx context.Context, opts v1.ListOptions) (*longhornv1beta2.DiskScheduleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *longhornv1beta2.DiskSchedule, err error)
	Apply(ctx context.Context, diskSchedule *applyconfigurationlonghornv1beta2.DiskScheduleApplyConfiguration, opts v1.ApplyOptions) (result *longhornv1beta2.DiskSchedule, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, diskSchedule *applyconfigurationlonghornv1beta2.DiskScheduleApplyConfiguration, opts v1.ApplyOptions) (result *longhornv1beta2.DiskSchedule, err error)
	DiskScheduleExpansion
}

// diskSchedules implements DiskScheduleInterface
type diskSchedules struct {
	*gentype.ClientWithListAndApply[*longhornv1beta2.DiskSchedule, *longhornv1beta2.DiskScheduleList, *applyconfigurationlonghornv1beta2.DiskScheduleApplyConfiguration]
}

// newDiskSchedules returns a DiskSchedules
func newDiskSchedules(c *LonghornV1beta2Client, namespace string) *diskSchedules {
	return &diskSchedules{
		gentype.NewClientWithListAndApply[*longhornv1beta2.DiskSchedule, *longhornv1beta2.DiskScheduleList, *applyconfigurationlonghornv1beta2.DiskScheduleApplyConfiguration](
			"diskschedules",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *longhornv1beta2.DiskSchedule { return &longhornv1beta2.DiskSchedule{} },
			func() *longhornv1beta2.DiskScheduleList { return &longhornv1beta2.DiskScheduleList{} },
		),
	}
}
