/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	"time"

	v1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	scheme "github.com/longhorn/longhorn-manager/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeDataEngineUpgradesGetter has a method to return a NodeDataEngineUpgradeInterface.
// A group's client should implement this interface.
type NodeDataEngineUpgradesGetter interface {
	NodeDataEngineUpgrades(namespace string) NodeDataEngineUpgradeInterface
}

// NodeDataEngineUpgradeInterface has methods to work with NodeDataEngineUpgrade resources.
type NodeDataEngineUpgradeInterface interface {
	Create(ctx context.Context, nodeDataEngineUpgrade *v1beta2.NodeDataEngineUpgrade, opts v1.CreateOptions) (*v1beta2.NodeDataEngineUpgrade, error)
	Update(ctx context.Context, nodeDataEngineUpgrade *v1beta2.NodeDataEngineUpgrade, opts v1.UpdateOptions) (*v1beta2.NodeDataEngineUpgrade, error)
	UpdateStatus(ctx context.Context, nodeDataEngineUpgrade *v1beta2.NodeDataEngineUpgrade, opts v1.UpdateOptions) (*v1beta2.NodeDataEngineUpgrade, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta2.NodeDataEngineUpgrade, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.NodeDataEngineUpgradeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.NodeDataEngineUpgrade, err error)
	NodeDataEngineUpgradeExpansion
}

// nodeDataEngineUpgrades implements NodeDataEngineUpgradeInterface
type nodeDataEngineUpgrades struct {
	client rest.Interface
	ns     string
}

// newNodeDataEngineUpgrades returns a NodeDataEngineUpgrades
func newNodeDataEngineUpgrades(c *LonghornV1beta2Client, namespace string) *nodeDataEngineUpgrades {
	return &nodeDataEngineUpgrades{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeDataEngineUpgrade, and returns the corresponding nodeDataEngineUpgrade object, and an error if there is any.
func (c *nodeDataEngineUpgrades) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.NodeDataEngineUpgrade, err error) {
	result = &v1beta2.NodeDataEngineUpgrade{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodedataengineupgrades").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeDataEngineUpgrades that match those selectors.
func (c *nodeDataEngineUpgrades) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.NodeDataEngineUpgradeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.NodeDataEngineUpgradeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodedataengineupgrades").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeDataEngineUpgrades.
func (c *nodeDataEngineUpgrades) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodedataengineupgrades").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeDataEngineUpgrade and creates it.  Returns the server's representation of the nodeDataEngineUpgrade, and an error, if there is any.
func (c *nodeDataEngineUpgrades) Create(ctx context.Context, nodeDataEngineUpgrade *v1beta2.NodeDataEngineUpgrade, opts v1.CreateOptions) (result *v1beta2.NodeDataEngineUpgrade, err error) {
	result = &v1beta2.NodeDataEngineUpgrade{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodedataengineupgrades").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDataEngineUpgrade).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeDataEngineUpgrade and updates it. Returns the server's representation of the nodeDataEngineUpgrade, and an error, if there is any.
func (c *nodeDataEngineUpgrades) Update(ctx context.Context, nodeDataEngineUpgrade *v1beta2.NodeDataEngineUpgrade, opts v1.UpdateOptions) (result *v1beta2.NodeDataEngineUpgrade, err error) {
	result = &v1beta2.NodeDataEngineUpgrade{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodedataengineupgrades").
		Name(nodeDataEngineUpgrade.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDataEngineUpgrade).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nodeDataEngineUpgrades) UpdateStatus(ctx context.Context, nodeDataEngineUpgrade *v1beta2.NodeDataEngineUpgrade, opts v1.UpdateOptions) (result *v1beta2.NodeDataEngineUpgrade, err error) {
	result = &v1beta2.NodeDataEngineUpgrade{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodedataengineupgrades").
		Name(nodeDataEngineUpgrade.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDataEngineUpgrade).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeDataEngineUpgrade and deletes it. Returns an error if one occurs.
func (c *nodeDataEngineUpgrades) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodedataengineupgrades").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeDataEngineUpgrades) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodedataengineupgrades").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeDataEngineUpgrade.
func (c *nodeDataEngineUpgrades) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.NodeDataEngineUpgrade, err error) {
	result = &v1beta2.NodeDataEngineUpgrade{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodedataengineupgrades").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
