/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	"time"

	v1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	scheme "github.com/longhorn/longhorn-manager/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ObjectEndpointsGetter has a method to return a ObjectEndpointInterface.
// A group's client should implement this interface.
type ObjectEndpointsGetter interface {
	ObjectEndpoints() ObjectEndpointInterface
}

// ObjectEndpointInterface has methods to work with ObjectEndpoint resources.
type ObjectEndpointInterface interface {
	Create(ctx context.Context, objectEndpoint *v1beta2.ObjectEndpoint, opts v1.CreateOptions) (*v1beta2.ObjectEndpoint, error)
	Update(ctx context.Context, objectEndpoint *v1beta2.ObjectEndpoint, opts v1.UpdateOptions) (*v1beta2.ObjectEndpoint, error)
	UpdateStatus(ctx context.Context, objectEndpoint *v1beta2.ObjectEndpoint, opts v1.UpdateOptions) (*v1beta2.ObjectEndpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta2.ObjectEndpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.ObjectEndpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.ObjectEndpoint, err error)
	ObjectEndpointExpansion
}

// objectEndpoints implements ObjectEndpointInterface
type objectEndpoints struct {
	client rest.Interface
}

// newObjectEndpoints returns a ObjectEndpoints
func newObjectEndpoints(c *LonghornV1beta2Client) *objectEndpoints {
	return &objectEndpoints{
		client: c.RESTClient(),
	}
}

// Get takes name of the objectEndpoint, and returns the corresponding objectEndpoint object, and an error if there is any.
func (c *objectEndpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.ObjectEndpoint, err error) {
	result = &v1beta2.ObjectEndpoint{}
	err = c.client.Get().
		Resource("objectendpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ObjectEndpoints that match those selectors.
func (c *objectEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.ObjectEndpointList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.ObjectEndpointList{}
	err = c.client.Get().
		Resource("objectendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested objectEndpoints.
func (c *objectEndpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("objectendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a objectEndpoint and creates it.  Returns the server's representation of the objectEndpoint, and an error, if there is any.
func (c *objectEndpoints) Create(ctx context.Context, objectEndpoint *v1beta2.ObjectEndpoint, opts v1.CreateOptions) (result *v1beta2.ObjectEndpoint, err error) {
	result = &v1beta2.ObjectEndpoint{}
	err = c.client.Post().
		Resource("objectendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(objectEndpoint).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a objectEndpoint and updates it. Returns the server's representation of the objectEndpoint, and an error, if there is any.
func (c *objectEndpoints) Update(ctx context.Context, objectEndpoint *v1beta2.ObjectEndpoint, opts v1.UpdateOptions) (result *v1beta2.ObjectEndpoint, err error) {
	result = &v1beta2.ObjectEndpoint{}
	err = c.client.Put().
		Resource("objectendpoints").
		Name(objectEndpoint.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(objectEndpoint).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *objectEndpoints) UpdateStatus(ctx context.Context, objectEndpoint *v1beta2.ObjectEndpoint, opts v1.UpdateOptions) (result *v1beta2.ObjectEndpoint, err error) {
	result = &v1beta2.ObjectEndpoint{}
	err = c.client.Put().
		Resource("objectendpoints").
		Name(objectEndpoint.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(objectEndpoint).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the objectEndpoint and deletes it. Returns an error if one occurs.
func (c *objectEndpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("objectendpoints").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *objectEndpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("objectendpoints").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched objectEndpoint.
func (c *objectEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.ObjectEndpoint, err error) {
	result = &v1beta2.ObjectEndpoint{}
	err = c.client.Patch(pt).
		Resource("objectendpoints").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
