// Code generated by protoc-gen-go. DO NOT EDIT.
// source: forwarder.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	forwarder.proto

It has these top-level messages:
	InstanceOperationRequest
	InstanceOperationResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InstanceOperationRequest struct {
	Type         string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	NodeID       string   `protobuf:"bytes,2,opt,name=nodeID" json:"nodeID,omitempty"`
	InstanceID   string   `protobuf:"bytes,3,opt,name=instanceID" json:"instanceID,omitempty"`
	InstanceName string   `protobuf:"bytes,4,opt,name=instanceName" json:"instanceName,omitempty"`
	VolumeName   string   `protobuf:"bytes,5,opt,name=volumeName" json:"volumeName,omitempty"`
	VolumeSize   int64    `protobuf:"varint,6,opt,name=volumeSize" json:"volumeSize,omitempty"`
	ReplicaURLs  []string `protobuf:"bytes,7,rep,name=replicaURLs" json:"replicaURLs,omitempty"`
}

func (m *InstanceOperationRequest) Reset()                    { *m = InstanceOperationRequest{} }
func (m *InstanceOperationRequest) String() string            { return proto.CompactTextString(m) }
func (*InstanceOperationRequest) ProtoMessage()               {}
func (*InstanceOperationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InstanceOperationRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *InstanceOperationRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *InstanceOperationRequest) GetInstanceID() string {
	if m != nil {
		return m.InstanceID
	}
	return ""
}

func (m *InstanceOperationRequest) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *InstanceOperationRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *InstanceOperationRequest) GetVolumeSize() int64 {
	if m != nil {
		return m.VolumeSize
	}
	return 0
}

func (m *InstanceOperationRequest) GetReplicaURLs() []string {
	if m != nil {
		return m.ReplicaURLs
	}
	return nil
}

type InstanceOperationResponse struct {
	InstanceID   string `protobuf:"bytes,1,opt,name=instanceID" json:"instanceID,omitempty"`
	InstanceName string `protobuf:"bytes,2,opt,name=instanceName" json:"instanceName,omitempty"`
	Running      bool   `protobuf:"varint,3,opt,name=running" json:"running,omitempty"`
	Ip           string `protobuf:"bytes,4,opt,name=ip" json:"ip,omitempty"`
}

func (m *InstanceOperationResponse) Reset()                    { *m = InstanceOperationResponse{} }
func (m *InstanceOperationResponse) String() string            { return proto.CompactTextString(m) }
func (*InstanceOperationResponse) ProtoMessage()               {}
func (*InstanceOperationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InstanceOperationResponse) GetInstanceID() string {
	if m != nil {
		return m.InstanceID
	}
	return ""
}

func (m *InstanceOperationResponse) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *InstanceOperationResponse) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *InstanceOperationResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func init() {
	proto.RegisterType((*InstanceOperationRequest)(nil), "pb.InstanceOperationRequest")
	proto.RegisterType((*InstanceOperationResponse)(nil), "pb.InstanceOperationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Forwarder service

type ForwarderClient interface {
	InstanceOperationRPC(ctx context.Context, in *InstanceOperationRequest, opts ...grpc.CallOption) (*InstanceOperationResponse, error)
}

type forwarderClient struct {
	cc *grpc.ClientConn
}

func NewForwarderClient(cc *grpc.ClientConn) ForwarderClient {
	return &forwarderClient{cc}
}

func (c *forwarderClient) InstanceOperationRPC(ctx context.Context, in *InstanceOperationRequest, opts ...grpc.CallOption) (*InstanceOperationResponse, error) {
	out := new(InstanceOperationResponse)
	err := grpc.Invoke(ctx, "/pb.Forwarder/InstanceOperationRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Forwarder service

type ForwarderServer interface {
	InstanceOperationRPC(context.Context, *InstanceOperationRequest) (*InstanceOperationResponse, error)
}

func RegisterForwarderServer(s *grpc.Server, srv ForwarderServer) {
	s.RegisterService(&_Forwarder_serviceDesc, srv)
}

func _Forwarder_InstanceOperationRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwarderServer).InstanceOperationRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Forwarder/InstanceOperationRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwarderServer).InstanceOperationRPC(ctx, req.(*InstanceOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Forwarder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Forwarder",
	HandlerType: (*ForwarderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstanceOperationRPC",
			Handler:    _Forwarder_InstanceOperationRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forwarder.proto",
}

func init() { proto.RegisterFile("forwarder.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x4d, 0x3b, 0x3b, 0x7b, 0x14, 0x85, 0x83, 0x48, 0x14, 0x95, 0xd2, 0xab, 0x5e, 0xf5,
	0x42, 0x1f, 0xc1, 0x21, 0x14, 0x44, 0x25, 0xb2, 0x07, 0x68, 0xb7, 0xa3, 0x04, 0xb6, 0x24, 0xa6,
	0xa9, 0xa2, 0x6f, 0xe0, 0xbb, 0xfa, 0x10, 0x62, 0xda, 0xb2, 0xaa, 0x1b, 0xde, 0xf5, 0x7c, 0xe7,
	0xf0, 0xd3, 0x2f, 0x3f, 0x1c, 0x3c, 0x6a, 0xfb, 0x5a, 0xda, 0x39, 0xd9, 0xdc, 0x58, 0xed, 0x34,
	0x06, 0xa6, 0x4a, 0x3f, 0x19, 0xf0, 0x42, 0xd5, 0xae, 0x54, 0x33, 0xba, 0x33, 0x64, 0x4b, 0x27,
	0xb5, 0x12, 0xf4, 0xdc, 0x50, 0xed, 0x10, 0x61, 0xe4, 0xde, 0x0c, 0x71, 0x96, 0xb0, 0x2c, 0x16,
	0xfe, 0x1b, 0x8f, 0x20, 0x52, 0x7a, 0x4e, 0xc5, 0x84, 0x07, 0x9e, 0x76, 0x13, 0x9e, 0x03, 0xc8,
	0x2e, 0xa7, 0x98, 0xf0, 0xd0, 0xef, 0x06, 0x04, 0x53, 0xd8, 0xeb, 0xa7, 0xdb, 0x72, 0x49, 0x7c,
	0xe4, 0x2f, 0x7e, 0xb0, 0xef, 0x8c, 0x17, 0xbd, 0x68, 0x96, 0xed, 0xc5, 0x76, 0x9b, 0xb1, 0x22,
	0xab, 0xfd, 0x83, 0x7c, 0x27, 0x1e, 0x25, 0x2c, 0x0b, 0xc5, 0x80, 0x60, 0x02, 0xbb, 0x96, 0xcc,
	0x42, 0xce, 0xca, 0xa9, 0xb8, 0xa9, 0xf9, 0x38, 0x09, 0xb3, 0x58, 0x0c, 0x51, 0xfa, 0xc1, 0xe0,
	0x78, 0x8d, 0x6e, 0x6d, 0xb4, 0xaa, 0xe9, 0x97, 0x03, 0xfb, 0xd7, 0x21, 0x58, 0xe3, 0xc0, 0x61,
	0x6c, 0x1b, 0xa5, 0xa4, 0x7a, 0xf2, 0x8f, 0xb0, 0x23, 0xfa, 0x11, 0xf7, 0x21, 0x90, 0xa6, 0xf3,
	0x0e, 0xa4, 0xb9, 0xa8, 0x20, 0xbe, 0xee, 0x1b, 0xc1, 0x29, 0x1c, 0xfe, 0xfd, 0xaf, 0xfb, 0x2b,
	0x3c, 0xcd, 0x4d, 0x95, 0x6f, 0x2a, 0xe8, 0xe4, 0x6c, 0xc3, 0xb6, 0xf5, 0x49, 0xb7, 0xaa, 0xc8,
	0x37, 0x7d, 0xf9, 0x15, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x48, 0x52, 0x9f, 0xfc, 0x01, 0x00, 0x00,
}
