/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta1"
	scheme "github.com/longhorn/longhorn-manager/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BackingImageManagersGetter has a method to return a BackingImageManagerInterface.
// A group's client should implement this interface.
type BackingImageManagersGetter interface {
	BackingImageManagers(namespace string) BackingImageManagerInterface
}

// BackingImageManagerInterface has methods to work with BackingImageManager resources.
type BackingImageManagerInterface interface {
	Create(*v1beta1.BackingImageManager) (*v1beta1.BackingImageManager, error)
	Update(*v1beta1.BackingImageManager) (*v1beta1.BackingImageManager, error)
	UpdateStatus(*v1beta1.BackingImageManager) (*v1beta1.BackingImageManager, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.BackingImageManager, error)
	List(opts v1.ListOptions) (*v1beta1.BackingImageManagerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackingImageManager, err error)
	BackingImageManagerExpansion
}

// backingImageManagers implements BackingImageManagerInterface
type backingImageManagers struct {
	client rest.Interface
	ns     string
}

// newBackingImageManagers returns a BackingImageManagers
func newBackingImageManagers(c *LonghornV1beta1Client, namespace string) *backingImageManagers {
	return &backingImageManagers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the backingImageManager, and returns the corresponding backingImageManager object, and an error if there is any.
func (c *backingImageManagers) Get(name string, options v1.GetOptions) (result *v1beta1.BackingImageManager, err error) {
	result = &v1beta1.BackingImageManager{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backingimagemanagers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BackingImageManagers that match those selectors.
func (c *backingImageManagers) List(opts v1.ListOptions) (result *v1beta1.BackingImageManagerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.BackingImageManagerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backingimagemanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested backingImageManagers.
func (c *backingImageManagers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("backingimagemanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a backingImageManager and creates it.  Returns the server's representation of the backingImageManager, and an error, if there is any.
func (c *backingImageManagers) Create(backingImageManager *v1beta1.BackingImageManager) (result *v1beta1.BackingImageManager, err error) {
	result = &v1beta1.BackingImageManager{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("backingimagemanagers").
		Body(backingImageManager).
		Do().
		Into(result)
	return
}

// Update takes the representation of a backingImageManager and updates it. Returns the server's representation of the backingImageManager, and an error, if there is any.
func (c *backingImageManagers) Update(backingImageManager *v1beta1.BackingImageManager) (result *v1beta1.BackingImageManager, err error) {
	result = &v1beta1.BackingImageManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backingimagemanagers").
		Name(backingImageManager.Name).
		Body(backingImageManager).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *backingImageManagers) UpdateStatus(backingImageManager *v1beta1.BackingImageManager) (result *v1beta1.BackingImageManager, err error) {
	result = &v1beta1.BackingImageManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backingimagemanagers").
		Name(backingImageManager.Name).
		SubResource("status").
		Body(backingImageManager).
		Do().
		Into(result)
	return
}

// Delete takes name of the backingImageManager and deletes it. Returns an error if one occurs.
func (c *backingImageManagers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backingimagemanagers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *backingImageManagers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backingimagemanagers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched backingImageManager.
func (c *backingImageManagers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackingImageManager, err error) {
	result = &v1beta1.BackingImageManager{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("backingimagemanagers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
