/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta1"
	scheme "github.com/longhorn/longhorn-manager/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BackingImagesGetter has a method to return a BackingImageInterface.
// A group's client should implement this interface.
type BackingImagesGetter interface {
	BackingImages(namespace string) BackingImageInterface
}

// BackingImageInterface has methods to work with BackingImage resources.
type BackingImageInterface interface {
	Create(*v1beta1.BackingImage) (*v1beta1.BackingImage, error)
	Update(*v1beta1.BackingImage) (*v1beta1.BackingImage, error)
	UpdateStatus(*v1beta1.BackingImage) (*v1beta1.BackingImage, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.BackingImage, error)
	List(opts v1.ListOptions) (*v1beta1.BackingImageList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackingImage, err error)
	BackingImageExpansion
}

// backingImages implements BackingImageInterface
type backingImages struct {
	client rest.Interface
	ns     string
}

// newBackingImages returns a BackingImages
func newBackingImages(c *LonghornV1beta1Client, namespace string) *backingImages {
	return &backingImages{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the backingImage, and returns the corresponding backingImage object, and an error if there is any.
func (c *backingImages) Get(name string, options v1.GetOptions) (result *v1beta1.BackingImage, err error) {
	result = &v1beta1.BackingImage{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backingimages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BackingImages that match those selectors.
func (c *backingImages) List(opts v1.ListOptions) (result *v1beta1.BackingImageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.BackingImageList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backingimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested backingImages.
func (c *backingImages) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("backingimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a backingImage and creates it.  Returns the server's representation of the backingImage, and an error, if there is any.
func (c *backingImages) Create(backingImage *v1beta1.BackingImage) (result *v1beta1.BackingImage, err error) {
	result = &v1beta1.BackingImage{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("backingimages").
		Body(backingImage).
		Do().
		Into(result)
	return
}

// Update takes the representation of a backingImage and updates it. Returns the server's representation of the backingImage, and an error, if there is any.
func (c *backingImages) Update(backingImage *v1beta1.BackingImage) (result *v1beta1.BackingImage, err error) {
	result = &v1beta1.BackingImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backingimages").
		Name(backingImage.Name).
		Body(backingImage).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *backingImages) UpdateStatus(backingImage *v1beta1.BackingImage) (result *v1beta1.BackingImage, err error) {
	result = &v1beta1.BackingImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backingimages").
		Name(backingImage.Name).
		SubResource("status").
		Body(backingImage).
		Do().
		Into(result)
	return
}

// Delete takes name of the backingImage and deletes it. Returns an error if one occurs.
func (c *backingImages) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backingimages").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *backingImages) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backingimages").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched backingImage.
func (c *backingImages) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackingImage, err error) {
	result = &v1beta1.BackingImage{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("backingimages").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
