---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "Simple passphrase"
  CRYPTO_KEY_PROVIDER: "secret" # this is optional we currently only support direct keys via secrets
  CRYPTO_KEY_CIPHER: "aes-xts-plain64" # this is optional, default value
  CRYPTO_KEY_HASH: "sha256" # this is optional, default value
  CRYPTO_KEY_SIZE: "256" # this is optional, default value
  CRYPTO_PBKDF: "argon2i" # this is optional, default value
