---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "Simple passphrase"
  CRYPTO_KEY_PROVIDER: "secret" # this is optional we currently only support direct keys via secrets
  CRYPTO_KEY_CIPHER: "aes-cbc-essiv:sha256" # this is optional, default value for RHEL
  CRYPTO_KEY_HASH: "sha256" # this is optional, default value
  CRYPTO_KEY_SIZE: "256" # this is optional, default value
  CRYPTO_PBKDF: "pbkdf2" # Only PBKDF2 is supported in FIPS mode, needs to be set on RHEL7
