#!/usr/bin/env bash

function usage() {
    cat << EOF

USAGE:
  # Must have Longhorn installed in "longhorn-system" namespace and have access to "kubectl" and the namespace
  # The volume should be state "attached"
  ./longhorn-engine-exec [volume-name] [longhorn-command-args]

EXAMPLE:
  ./longhorn-engine-exec test-vol snapshot ls
  ./longhorn-engine-exec test-vol info

EOF

}

if [[ $# -lt 2 ]]
then
    echo "Error: Require at least 2 parameters: [volume-name] and [longhorn-command-args]"
    usage
    exit 1
fi

kubectl -n longhorn-system get lhv $1 > /dev/null
if [[ $? -ne 0 ]]
then
    echo "Error: Volume $1 is not found in Longhorn system"
    exit 1
fi


OLD_IFS="$IFS"
IFS=$'\n';

for line in $(kubectl -n longhorn-system get lhe | grep "$1-e-.*")
do
    engineName=$(echo ${line} | sed "s/ .*//")
    engineInfo=$(kubectl -n longhorn-system get lhe ${engineName} -o yaml)
    engineVolume=$(echo "${engineInfo}" | grep "volumeName:" | sed "s/ *volumeName: *//")
    if [[ "$1" == "${engineVolume}" ]]
    then
        enginePort=$(echo "${engineInfo}" | grep "port:" | sed "s/ *port: *//")
        instanceManager=$(echo "${engineInfo}" | grep "instanceManagerName:" | sed "s/ *instanceManagerName: *//" | sed "s/\"//g")
        if [[ "${enginePort}" == "" ]]
        then
            echo "Error: Cannot find related port"
            exit 1
        fi
        if [[ "${instanceManager}" == "" ]]
        then
            echo "Error: Cannot find related instance manager, or the volume is not running and the instance manager is empty."
            usage
            exit 1
        fi

        array=( $@ )
        args=( ${array[@]:1} )

        kubectl -n longhorn-system exec -it ${instanceManager} -- bash -c "longhorn --url localhost:${enginePort} ${args[@]}"

        exit 0
    fi
done

echo "Error: Cannot find related engine for volume $1"
exit 1
