apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: longhorn-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-role
subjects:
- kind: ServiceAccount
  name: longhorn-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: longhorn-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: ["longhorn.rancher.io"]
  resources: ["nodes"]
  verbs: ["*"]
- apiGroups: ["longhorn.rancher.io"]
  resources: ["volumes"]
  verbs: ["*"]
- apiGroups: ["longhorn.rancher.io"]
  resources: ["replicas"]
  verbs: ["*"]
- apiGroups: ["longhorn.rancher.io"]
  resources: ["settings"]
  verbs: ["*"]
- apiGroups: ["longhorn.rancher.io"]
  resources: ["controllers"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: longhorn-operator
  name: longhorn-operator
spec:
  template:
    metadata:
      labels:
        k8s-app: longhorn-operator
    spec:
      initContainers:
      - name: init-container
#replace it with your own longhorn-engine here
        image: rancher/longhorn-engine:17e33fc
        command: ['sh', '-c', 'cp /usr/local/bin/* /data/']
        volumeMounts:
        - name: execbin
          mountPath: /data/
      containers:
      - name: longhorn-container
#replace it with your own longhorn-manager here
        image: longhorn-manager:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["/launch-manager"]
        args:
#replace it with your own longhorn-engine and different the way of orchestrator
        - "--orchestrator docker   --engine-image rancher/longhorn-engine:17e33fc"
        ports:
        - containerPort: 9500
          name: manager
        volumeMounts:
        - name: dev
          mountPath: /host/dev/
        - name: varrun
          mountPath: /var/run/
        - name: longhorn
          mountPath: /var/lib/rancher/longhorn/
        - name: execbin
          mountPath: /usr/local/bin/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: dev
        hostPath:
          path: /dev/
      - name: varrun
        hostPath:
          path: /var/run/
      - name: longhorn
        hostPath:
          path: /var/lib/rancher/longhorn/
      - name: execbin
        emptyDir: {}
      serviceAccountName: longhorn-service-account
---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: longhorn-operator
  name: longhorn-operator-svc
spec:
  selector:
    k8s-app: longhorn-operator
  ports:
  - name: manager
    port: 9500
    targetPort: manager
  sessionAffinity: ClientIP
