/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1alpha1

// EngineListerExpansion allows custom methods to be added to
// EngineLister.
type EngineListerExpansion interface{}

// EngineNamespaceListerExpansion allows custom methods to be added to
// EngineNamespaceLister.
type EngineNamespaceListerExpansion interface{}

// ReplicaListerExpansion allows custom methods to be added to
// ReplicaLister.
type ReplicaListerExpansion interface{}

// ReplicaNamespaceListerExpansion allows custom methods to be added to
// ReplicaNamespaceLister.
type ReplicaNamespaceListerExpansion interface{}

// SettingListerExpansion allows custom methods to be added to
// SettingLister.
type SettingListerExpansion interface{}

// SettingNamespaceListerExpansion allows custom methods to be added to
// SettingNamespaceLister.
type SettingNamespaceListerExpansion interface{}

// VolumeListerExpansion allows custom methods to be added to
// VolumeLister.
type VolumeListerExpansion interface{}

// VolumeNamespaceListerExpansion allows custom methods to be added to
// VolumeNamespaceLister.
type VolumeNamespaceListerExpansion interface{}
