/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeObjectStores implements ObjectStoreInterface
type FakeObjectStores struct {
	Fake *FakeLonghornV1beta2
	ns   string
}

var objectstoresResource = schema.GroupVersionResource{Group: "longhorn.io", Version: "v1beta2", Resource: "objectstores"}

var objectstoresKind = schema.GroupVersionKind{Group: "longhorn.io", Version: "v1beta2", Kind: "ObjectStore"}

// Get takes name of the objectStore, and returns the corresponding objectStore object, and an error if there is any.
func (c *FakeObjectStores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.ObjectStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(objectstoresResource, c.ns, name), &v1beta2.ObjectStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.ObjectStore), err
}

// List takes label and field selectors, and returns the list of ObjectStores that match those selectors.
func (c *FakeObjectStores) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.ObjectStoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(objectstoresResource, objectstoresKind, c.ns, opts), &v1beta2.ObjectStoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.ObjectStoreList{ListMeta: obj.(*v1beta2.ObjectStoreList).ListMeta}
	for _, item := range obj.(*v1beta2.ObjectStoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested objectStores.
func (c *FakeObjectStores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(objectstoresResource, c.ns, opts))

}

// Create takes the representation of a objectStore and creates it.  Returns the server's representation of the objectStore, and an error, if there is any.
func (c *FakeObjectStores) Create(ctx context.Context, objectStore *v1beta2.ObjectStore, opts v1.CreateOptions) (result *v1beta2.ObjectStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(objectstoresResource, c.ns, objectStore), &v1beta2.ObjectStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.ObjectStore), err
}

// Update takes the representation of a objectStore and updates it. Returns the server's representation of the objectStore, and an error, if there is any.
func (c *FakeObjectStores) Update(ctx context.Context, objectStore *v1beta2.ObjectStore, opts v1.UpdateOptions) (result *v1beta2.ObjectStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(objectstoresResource, c.ns, objectStore), &v1beta2.ObjectStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.ObjectStore), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeObjectStores) UpdateStatus(ctx context.Context, objectStore *v1beta2.ObjectStore, opts v1.UpdateOptions) (*v1beta2.ObjectStore, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(objectstoresResource, "status", c.ns, objectStore), &v1beta2.ObjectStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.ObjectStore), err
}

// Delete takes name of the objectStore and deletes it. Returns an error if one occurs.
func (c *FakeObjectStores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(objectstoresResource, c.ns, name), &v1beta2.ObjectStore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeObjectStores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(objectstoresResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta2.ObjectStoreList{})
	return err
}

// Patch applies the patch and returns the patched objectStore.
func (c *FakeObjectStores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.ObjectStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(objectstoresResource, c.ns, name, pt, data, subresources...), &v1beta2.ObjectStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.ObjectStore), err
}
