#!/bin/bash
set -e -x

source $(dirname $0)/version

LINKFLAGS="-X github.com/longhorn/longhorn-manager/meta.Version=$VERSION
           -X github.com/longhorn/longhorn-manager/meta.GitCommit=$GITCOMMIT
           -X github.com/longhorn/longhorn-manager/meta.BuildDate=$BUILDDATE"
[ "$(uname)" != "Darwin" ] && OTHER_LINKFLAGS="-extldflags -static -s"

cd $(dirname $0)/..

mkdir -p bin

CGO_ENABLED=0 GOARCH=amd64 go build -o bin/longhorn-manager-amd64 -ldflags "$LINKFLAGS $OTHER_LINKFLAGS"
CGO_ENABLED=0 GOARCH=arm64 go build -o bin/longhorn-manager-arm64 -ldflags "$LINKFLAGS $OTHER_LINKFLAGS"
