#!/bin/bash
set -e

cd $(dirname $0)

./build
./validate
./test -cover
./package
./package-driver

image=`cat ../bin/latest_image`
drv_image=`cat ../bin/latest_driver_image`

echo
echo Longhorn Manager image: ${image}
echo Longhorn Driver image: ${drv_image}
