#!/bin/bash
set -e

cd $(dirname $0)/..

package=$1

if [ "${package}" == "" ]; then
        echo Require package name for test coverage output
        exit 1
fi

mount --bind /host/dev /dev

source ./scripts/common.sh

# Removing any existing testing containers, e.g. from scripts/server
cleanup_mgr_test

trap cleanup_mgr_test EXIT

start_etcd
etcd_ip=$(get_container_ip $ETCD_SERVER)
wait_for_etcd $etcd_ip

export LONGHORN_MANAGER_TEST_COMP="true"
export LONGHORN_MANAGER_TEST_ETCD_SERVER="$etcd_ip"
export LONGHORN_ENGINE_IMAGE="${LONGHORN_ENGINE_IMAGE}"

docker inspect ${LONGHORN_ENGINE_IMAGE} >/dev/null || docker pull ${LONGHORN_ENGINE_IMAGE}

echo Running test coverage

echo Package: ${package}

[ "${ARCH}" == "amd64" ] && RACE=-race
go test ${RACE} -coverprofile=bin/coverage.out ./${package}
