#!/bin/bash
set -e

cd $(dirname $0)/..

if [ ! -x ./bin/latest_image ]; then
    ./scripts/package
fi

source ./scripts/common.sh

image=`cat ./bin/latest_image`

# Removing any existing testing containers, e.g. from scripts/server
cleanup_mgr_test

trap cleanup_mgr_test EXIT

start_etcd

etcd_ip=$(get_container_ip $ETCD_SERVER)
wait_for_etcd $etcd_ip

start_nfs
nfs_ip=$(get_container_ip $NFS_SERVER)

start_engine_binary

image=`cat ./bin/latest_image`

mgr1="${LONGHORN_MANAGER_NAME}-1"
start_mgr $image $mgr1 ${etcd_ip}
mgr1_ip=$(get_container_ip ${mgr1})
wait_for_mgr ${mgr1_ip}

echo $mgr1 is ready

mgr2="${LONGHORN_MANAGER_NAME}-2"
start_mgr $image $mgr2 ${etcd_ip}
mgr2_ip=$(get_container_ip ${mgr2})
wait_for_mgr ${mgr2_ip}

echo $mgr2 is ready

mgr3="${LONGHORN_MANAGER_NAME}-3"
start_mgr $image $mgr3 ${etcd_ip}
mgr3_ip=$(get_container_ip ${mgr3})
wait_for_mgr ${mgr3_ip}

echo $mgr3 is ready

export LONGHORN_MANAGER_TEST_SERVER_IPS="$mgr1_ip,$mgr2_ip,$mgr3_ip"
export LONGHORN_MANAGER_TEST_BACKUPSTORE_URL="nfs://${nfs_ip}:${BACKUPSTORE_PATH}"

cd integration
find -depth -name __pycache__ -o -name "*.pyc" -exec rm -rf {} \;
if [ -z "$NO_TEST" ]; then
    tox "$@"
fi
