#!/bin/bash
set -e

cd $(dirname $0)/..

ARCH=${ARCH:-amd64}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

export VERSION=${VERSION:-$(./scripts/version)}

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}
IMAGE=${IMAGE:-${REPO}/longhorn-driver:${TAG}}

cd driver
docker build -t ${IMAGE} ./build

cd ..

echo Built ${IMAGE}

echo ${IMAGE} > ./bin/latest_driver_image
