#!/bin/bash
set -e

cd $(dirname $0)/..

if [ ! -x ./bin/latest_image ]; then
    ./scripts/package
fi

source ./scripts/common.sh

image=`cat ./bin/latest_image`

mount --bind /host/dev /dev

start_etcd

etcd_ip=$(get_container_ip $ETCD_SERVER)
wait_for_etcd $etcd_ip

start_nfs
nfs_ip=$(get_container_ip $NFS_SERVER)

start_engine_binary

image=`cat ./bin/latest_image`

echo NFS backupstore at: nfs://${nfs_ip}:${BACKUPSTORE_PATH}

mgr=${LONGHORN_MANAGER_NAME}-0
# persist the host UUID and expose the port
start_mgr $image $mgr $etcd_ip -p 9500:9500 \
        -v /var/lib/rancher/longhorn:/var/lib/rancher/longhorn
