#!/bin/bash
set -e

cd "$(dirname "$0")/.."

args=("$@")

echo Running tests

if ! git diff --name-only | grep -Ev '(.git|.trash-cache|vendor|bin|k8s)' | grep -E '.*\.go' ; then
  PACKAGES="$(find . -name '*.go' | xargs -I{} dirname {} | sort -u | grep -Ev '(.git|.trash-cache|vendor|bin|k8s)')"
else
  PACKAGES="$(git diff --name-only | grep -E '.*\.go' | xargs -I{} dirname ./{} | sort -u | grep -Ev '(.git|.trash-cache|vendor|bin|k8s)')"
fi

echo Packages: "${PACKAGES}"

[ "${ARCH}" == "amd64" ] && RACE=-race
go test "${RACE}" "${args[@]}" ${PACKAGES}
