#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

PACKAGES="$(find . -name '*.go' | grep -Ev '.pb.go' | xargs -I{} dirname {} | \
	sort -u | grep -Ev '(.git|.trash-cache|vendor|bin|k8s/pkg|client)')"

echo Packages: ${PACKAGES}

echo Running: go vet
go vet ${PACKAGES}

echo Running: golangci-lint
golangci-lint run --timeout=5m

echo Running: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
