/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	longhorn_v1alpha1 "github.com/rancher/longhorn-manager/k8s/pkg/apis/longhorn/v1alpha1"
	versioned "github.com/rancher/longhorn-manager/k8s/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/rancher/longhorn-manager/k8s/pkg/client/listers/longhorn/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ReplicaInformer provides access to a shared informer and lister for
// Replicas.
type ReplicaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ReplicaLister
}

type replicaInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewReplicaInformer constructs a new informer for Replica type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewReplicaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.LonghornV1alpha1().Replicas(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.LonghornV1alpha1().Replicas(namespace).Watch(options)
			},
		},
		&longhorn_v1alpha1.Replica{},
		resyncPeriod,
		indexers,
	)
}

func defaultReplicaInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewReplicaInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *replicaInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&longhorn_v1alpha1.Replica{}, defaultReplicaInformer)
}

func (f *replicaInformer) Lister() v1alpha1.ReplicaLister {
	return v1alpha1.NewReplicaLister(f.Informer().GetIndexer())
}
