// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	manager.proto

It has these top-level messages:
	NodeNotifyRequest
	NodeNotifyResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeNotifyRequest struct {
	Event      string `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	VolumeName string `protobuf:"bytes,2,opt,name=volumeName" json:"volumeName,omitempty"`
}

func (m *NodeNotifyRequest) Reset()                    { *m = NodeNotifyRequest{} }
func (m *NodeNotifyRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeNotifyRequest) ProtoMessage()               {}
func (*NodeNotifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeNotifyRequest) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *NodeNotifyRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

type NodeNotifyResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *NodeNotifyResponse) Reset()                    { *m = NodeNotifyResponse{} }
func (m *NodeNotifyResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeNotifyResponse) ProtoMessage()               {}
func (*NodeNotifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeNotifyResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeNotifyRequest)(nil), "pb.NodeNotifyRequest")
	proto.RegisterType((*NodeNotifyResponse)(nil), "pb.NodeNotifyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Manager service

type ManagerClient interface {
	NodeNotifyRPC(ctx context.Context, in *NodeNotifyRequest, opts ...grpc.CallOption) (*NodeNotifyResponse, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) NodeNotifyRPC(ctx context.Context, in *NodeNotifyRequest, opts ...grpc.CallOption) (*NodeNotifyResponse, error) {
	out := new(NodeNotifyResponse)
	err := grpc.Invoke(ctx, "/pb.Manager/NodeNotifyRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Manager service

type ManagerServer interface {
	NodeNotifyRPC(context.Context, *NodeNotifyRequest) (*NodeNotifyResponse, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_NodeNotifyRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).NodeNotifyRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Manager/NodeNotifyRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).NodeNotifyRPC(ctx, req.(*NodeNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeNotifyRPC",
			Handler:    _Manager_NodeNotifyRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager.proto",
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0xcc, 0x4b,
	0x4c, 0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xf2, 0xe4,
	0x12, 0xf4, 0xcb, 0x4f, 0x49, 0xf5, 0xcb, 0x2f, 0xc9, 0x4c, 0xab, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x4d, 0x2d, 0x4b, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0x70, 0x84, 0xe4, 0xb8, 0xb8, 0xca, 0xf2, 0x73, 0x4a, 0x73, 0x53, 0xfd, 0x12,
	0x73, 0x53, 0x25, 0x98, 0xc0, 0x52, 0x48, 0x22, 0x4a, 0x3a, 0x5c, 0x42, 0xc8, 0x46, 0x15, 0x17,
	0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0xa5, 0x16, 0x97, 0xe6, 0xc0, 0x0c, 0x83,
	0xf2, 0x8c, 0xbc, 0xb9, 0xd8, 0x7d, 0x21, 0xae, 0x11, 0x72, 0xe0, 0xe2, 0x45, 0xd2, 0x18, 0xe0,
	0x2c, 0x24, 0xaa, 0x57, 0x90, 0xa4, 0x87, 0xe1, 0x2c, 0x29, 0x31, 0x74, 0x61, 0x88, 0x15, 0x4a,
	0x0c, 0x49, 0x6c, 0x60, 0x0f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x81, 0xd4, 0xfc, 0x97,
	0xe1, 0x00, 0x00, 0x00,
}
