/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EngineFrontendLister helps list EngineFrontends.
// All objects returned here must be treated as read-only.
type EngineFrontendLister interface {
	// List lists all EngineFrontends in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.EngineFrontend, err error)
	// EngineFrontends returns an object that can list and get EngineFrontends.
	EngineFrontends(namespace string) EngineFrontendNamespaceLister
	EngineFrontendListerExpansion
}

// engineFrontendLister implements the EngineFrontendLister interface.
type engineFrontendLister struct {
	listers.ResourceIndexer[*longhornv1beta2.EngineFrontend]
}

// NewEngineFrontendLister returns a new EngineFrontendLister.
func NewEngineFrontendLister(indexer cache.Indexer) EngineFrontendLister {
	return &engineFrontendLister{listers.New[*longhornv1beta2.EngineFrontend](indexer, longhornv1beta2.Resource("enginefrontend"))}
}

// EngineFrontends returns an object that can list and get EngineFrontends.
func (s *engineFrontendLister) EngineFrontends(namespace string) EngineFrontendNamespaceLister {
	return engineFrontendNamespaceLister{listers.NewNamespaced[*longhornv1beta2.EngineFrontend](s.ResourceIndexer, namespace)}
}

// EngineFrontendNamespaceLister helps list and get EngineFrontends.
// All objects returned here must be treated as read-only.
type EngineFrontendNamespaceLister interface {
	// List lists all EngineFrontends in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.EngineFrontend, err error)
	// Get retrieves the EngineFrontend from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*longhornv1beta2.EngineFrontend, error)
	EngineFrontendNamespaceListerExpansion
}

// engineFrontendNamespaceLister implements the EngineFrontendNamespaceLister
// interface.
type engineFrontendNamespaceLister struct {
	listers.ResourceIndexer[*longhornv1beta2.EngineFrontend]
}
