/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"

	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// InstanceManagerUpgradeControlLister helps list InstanceManagerUpgradeControls.
// All objects returned here must be treated as read-only.
type InstanceManagerUpgradeControlLister interface {
	// List lists all InstanceManagerUpgradeControls in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.InstanceManagerUpgradeControl, err error)
	// InstanceManagerUpgradeControls returns an object that can list and get InstanceManagerUpgradeControls.
	InstanceManagerUpgradeControls(namespace string) InstanceManagerUpgradeControlNamespaceLister
	InstanceManagerUpgradeControlListerExpansion
}

// instanceManagerUpgradeControlLister implements the InstanceManagerUpgradeControlLister interface.
type instanceManagerUpgradeControlLister struct {
	listers.ResourceIndexer[*longhornv1beta2.InstanceManagerUpgradeControl]
}

// NewInstanceManagerUpgradeControlLister returns a new InstanceManagerUpgradeControlLister.
func NewInstanceManagerUpgradeControlLister(indexer cache.Indexer) InstanceManagerUpgradeControlLister {
	return &instanceManagerUpgradeControlLister{listers.New[*longhornv1beta2.InstanceManagerUpgradeControl](indexer, longhornv1beta2.Resource("instancemanagerupgradecontrol"))}
}

// InstanceManagerUpgradeControls returns an object that can list and get InstanceManagerUpgradeControls.
func (s *instanceManagerUpgradeControlLister) InstanceManagerUpgradeControls(namespace string) InstanceManagerUpgradeControlNamespaceLister {
	return instanceManagerUpgradeControlNamespaceLister{listers.NewNamespaced[*longhornv1beta2.InstanceManagerUpgradeControl](s.ResourceIndexer, namespace)}
}

// InstanceManagerUpgradeControlNamespaceLister helps list and get InstanceManagerUpgradeControls.
// All objects returned here must be treated as read-only.
type InstanceManagerUpgradeControlNamespaceLister interface {
	// List lists all InstanceManagerUpgradeControls in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.InstanceManagerUpgradeControl, err error)
	// Get retrieves the InstanceManagerUpgradeControl from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*longhornv1beta2.InstanceManagerUpgradeControl, error)
	InstanceManagerUpgradeControlNamespaceListerExpansion
}

// instanceManagerUpgradeControlNamespaceLister implements the InstanceManagerUpgradeControlNamespaceLister
// interface.
type instanceManagerUpgradeControlNamespaceLister struct {
	listers.ResourceIndexer[*longhornv1beta2.InstanceManagerUpgradeControl]
}
