/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ShardLister helps list Shards.
// All objects returned here must be treated as read-only.
type ShardLister interface {
	// List lists all Shards in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.Shard, err error)
	// Shards returns an object that can list and get Shards.
	Shards(namespace string) ShardNamespaceLister
	ShardListerExpansion
}

// shardLister implements the ShardLister interface.
type shardLister struct {
	listers.ResourceIndexer[*longhornv1beta2.Shard]
}

// NewShardLister returns a new ShardLister.
func NewShardLister(indexer cache.Indexer) ShardLister {
	return &shardLister{listers.New[*longhornv1beta2.Shard](indexer, longhornv1beta2.Resource("shard"))}
}

// Shards returns an object that can list and get Shards.
func (s *shardLister) Shards(namespace string) ShardNamespaceLister {
	return shardNamespaceLister{listers.NewNamespaced[*longhornv1beta2.Shard](s.ResourceIndexer, namespace)}
}

// ShardNamespaceLister helps list and get Shards.
// All objects returned here must be treated as read-only.
type ShardNamespaceLister interface {
	// List lists all Shards in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.Shard, err error)
	// Get retrieves the Shard from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*longhornv1beta2.Shard, error)
	ShardNamespaceListerExpansion
}

// shardNamespaceLister implements the ShardNamespaceLister
// interface.
type shardNamespaceLister struct {
	listers.ResourceIndexer[*longhornv1beta2.Shard]
}
