/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ShardGroupLister helps list ShardGroups.
// All objects returned here must be treated as read-only.
type ShardGroupLister interface {
	// List lists all ShardGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.ShardGroup, err error)
	// ShardGroups returns an object that can list and get ShardGroups.
	ShardGroups(namespace string) ShardGroupNamespaceLister
	ShardGroupListerExpansion
}

// shardGroupLister implements the ShardGroupLister interface.
type shardGroupLister struct {
	listers.ResourceIndexer[*longhornv1beta2.ShardGroup]
}

// NewShardGroupLister returns a new ShardGroupLister.
func NewShardGroupLister(indexer cache.Indexer) ShardGroupLister {
	return &shardGroupLister{listers.New[*longhornv1beta2.ShardGroup](indexer, longhornv1beta2.Resource("shardgroup"))}
}

// ShardGroups returns an object that can list and get ShardGroups.
func (s *shardGroupLister) ShardGroups(namespace string) ShardGroupNamespaceLister {
	return shardGroupNamespaceLister{listers.NewNamespaced[*longhornv1beta2.ShardGroup](s.ResourceIndexer, namespace)}
}

// ShardGroupNamespaceLister helps list and get ShardGroups.
// All objects returned here must be treated as read-only.
type ShardGroupNamespaceLister interface {
	// List lists all ShardGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.ShardGroup, err error)
	// Get retrieves the ShardGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*longhornv1beta2.ShardGroup, error)
	ShardGroupNamespaceListerExpansion
}

// shardGroupNamespaceLister implements the ShardGroupNamespaceLister
// interface.
type shardGroupNamespaceLister struct {
	listers.ResourceIndexer[*longhornv1beta2.ShardGroup]
}
