/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SnapshotGroupLister helps list SnapshotGroups.
// All objects returned here must be treated as read-only.
type SnapshotGroupLister interface {
	// List lists all SnapshotGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.SnapshotGroup, err error)
	// SnapshotGroups returns an object that can list and get SnapshotGroups.
	SnapshotGroups(namespace string) SnapshotGroupNamespaceLister
	SnapshotGroupListerExpansion
}

// snapshotGroupLister implements the SnapshotGroupLister interface.
type snapshotGroupLister struct {
	listers.ResourceIndexer[*longhornv1beta2.SnapshotGroup]
}

// NewSnapshotGroupLister returns a new SnapshotGroupLister.
func NewSnapshotGroupLister(indexer cache.Indexer) SnapshotGroupLister {
	return &snapshotGroupLister{listers.New[*longhornv1beta2.SnapshotGroup](indexer, longhornv1beta2.Resource("snapshotgroup"))}
}

// SnapshotGroups returns an object that can list and get SnapshotGroups.
func (s *snapshotGroupLister) SnapshotGroups(namespace string) SnapshotGroupNamespaceLister {
	return snapshotGroupNamespaceLister{listers.NewNamespaced[*longhornv1beta2.SnapshotGroup](s.ResourceIndexer, namespace)}
}

// SnapshotGroupNamespaceLister helps list and get SnapshotGroups.
// All objects returned here must be treated as read-only.
type SnapshotGroupNamespaceLister interface {
	// List lists all SnapshotGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.SnapshotGroup, err error)
	// Get retrieves the SnapshotGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*longhornv1beta2.SnapshotGroup, error)
	SnapshotGroupNamespaceListerExpansion
}

// snapshotGroupNamespaceLister implements the SnapshotGroupNamespaceLister
// interface.
type snapshotGroupNamespaceLister struct {
	listers.ResourceIndexer[*longhornv1beta2.SnapshotGroup]
}
