# This is one of seven CRDs that were originally apiextensions.k8s.io/v1beta1. If Longhorn and Kubernetes are upgraded
# in a particular order from Longhorn v1.0.2- to the latest, preserveUnknownFields may remain true, even though the
# default (and intended value) is false.
# https://github.com/longhorn/longhorn/discussions/4198
# https://github.com/longhorn/longhorn/issues/7887
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: engines.longhorn.io
spec:
  preserveUnknownFields: false
