name: Codespell

on:
  push:
  pull_request:
    branches:
    - master
    - "v*.*.*"

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Check code spell
      uses: codespell-project/actions-codespell@v1
      with:
        check_filenames: true
        ignore_words_file: .codespellignore
        skip: "*/**.yaml,*/**.yml,./scripts,./vendor,MAINTAINERS,LICENSE,go.mod,go.sum"
