name: 'Close stale issues and PRs'

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  call-workflow:
    uses: longhorn/longhorn/.github/workflows/stale.yaml@666fcb2f9b7d50b60936ba517f71c44df4e4d482 # v1.11.2
