name: 'Close stale issues and PRs'

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  call-workflow:
    uses: longhorn/longhorn/.github/workflows/stale.yaml@9990b6db0c5971d5b3bc58dd14095fcdc3c761b3 # v1.12.0
