/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1alpha1"
	scheme "github.com/longhorn/longhorn-manager/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EngineImagesGetter has a method to return a EngineImageInterface.
// A group's client should implement this interface.
type EngineImagesGetter interface {
	EngineImages(namespace string) EngineImageInterface
}

// EngineImageInterface has methods to work with EngineImage resources.
type EngineImageInterface interface {
	Create(*v1alpha1.EngineImage) (*v1alpha1.EngineImage, error)
	Update(*v1alpha1.EngineImage) (*v1alpha1.EngineImage, error)
	UpdateStatus(*v1alpha1.EngineImage) (*v1alpha1.EngineImage, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.EngineImage, error)
	List(opts v1.ListOptions) (*v1alpha1.EngineImageList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EngineImage, err error)
	EngineImageExpansion
}

// engineImages implements EngineImageInterface
type engineImages struct {
	client rest.Interface
	ns     string
}

// newEngineImages returns a EngineImages
func newEngineImages(c *LonghornV1alpha1Client, namespace string) *engineImages {
	return &engineImages{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the engineImage, and returns the corresponding engineImage object, and an error if there is any.
func (c *engineImages) Get(name string, options v1.GetOptions) (result *v1alpha1.EngineImage, err error) {
	result = &v1alpha1.EngineImage{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("engineimages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EngineImages that match those selectors.
func (c *engineImages) List(opts v1.ListOptions) (result *v1alpha1.EngineImageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EngineImageList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("engineimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested engineImages.
func (c *engineImages) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("engineimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a engineImage and creates it.  Returns the server's representation of the engineImage, and an error, if there is any.
func (c *engineImages) Create(engineImage *v1alpha1.EngineImage) (result *v1alpha1.EngineImage, err error) {
	result = &v1alpha1.EngineImage{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("engineimages").
		Body(engineImage).
		Do().
		Into(result)
	return
}

// Update takes the representation of a engineImage and updates it. Returns the server's representation of the engineImage, and an error, if there is any.
func (c *engineImages) Update(engineImage *v1alpha1.EngineImage) (result *v1alpha1.EngineImage, err error) {
	result = &v1alpha1.EngineImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("engineimages").
		Name(engineImage.Name).
		Body(engineImage).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *engineImages) UpdateStatus(engineImage *v1alpha1.EngineImage) (result *v1alpha1.EngineImage, err error) {
	result = &v1alpha1.EngineImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("engineimages").
		Name(engineImage.Name).
		SubResource("status").
		Body(engineImage).
		Do().
		Into(result)
	return
}

// Delete takes name of the engineImage and deletes it. Returns an error if one occurs.
func (c *engineImages) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("engineimages").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *engineImages) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("engineimages").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched engineImage.
func (c *engineImages) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EngineImage, err error) {
	result = &v1alpha1.EngineImage{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("engineimages").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
